# Generated by Django 3.2.19 on 2023-05-31 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaxuser',
            name='ida_projects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='metaxuser',
            name='synced',
            field=models.DateTimeField(blank=True, help_text='When user data was synchronized from an external service.', null=True),
        ),
    ]
