# Generated by Django 4.2.17 on 2025-01-10 07:55

from django.utils import timezone
from django.db import migrations, models

def to_timestamp(apps, schema_editor):
    model = apps.get_model("users.MetaxUser")
    model.objects.filter(is_removed=True).update(removed=timezone.now())

def from_timestamp(apps, schema_editor):
    model = apps.get_model("users.MetaxUser")
    model.objects.filter(removed__isnull=False).update(is_removed=True)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaxuser',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(to_timestamp, from_timestamp),
        migrations.RemoveField(
            model_name='metaxuser',
            name='is_removed',
        ),
    ]
