# Generated by Django 3.2.22 on 2023-11-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230531_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaxuser',
            name='organization',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
