# Generated by Django 4.2.17 on 2025-04-09 14:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_old_authtokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaxuser',
            name='admin_organizations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, default=list, size=None),
        ),
    ]
