# Generated by Django 3.2.22 on 2024-02-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_metaxuser_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metaxuser',
            old_name='ida_projects',
            new_name='csc_projects',
        ),
        migrations.AddField(
            model_name='metaxuser',
            name='fairdata_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
