# Generated by Django 4.2.17 on 2025-06-03 06:47

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_metaxuser_admin_organizations'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='metaxuser',
            managers=[
                ('objects', apps.users.models.SoftDeletableMetaxUserManager()),
                ('available_objects', apps.users.models.SoftDeletableMetaxUserManager()),
                ('all_objects', apps.users.models.MetaxUserManager()),
            ],
        ),
    ]
