# Generated by Django 3.2.22 on 2024-02-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240213_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metaxuser',
            options={'ordering': ['username']},
        ),
    ]
