# Generated by Django 4.2.17 on 2025-08-15 07:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_metaxuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaxuser',
            name='dac_organizations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, default=list, help_text='Organizations where the user is a member of the Data Access Committee.', size=None),
        ),
    ]
