# Generated by Django 4.2.24 on 2025-10-28 11:36

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_metaxuser_dac_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOrganization',
            fields=[
                ('removed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='example: {"en":"title", "fi":"otsikko"}', null=True)),
                ('other_identifier', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'admin organization',
                'verbose_name_plural': 'admin organizations',
                'ordering': ['id'],
            },
        ),
    ]
