# Generated by Django 4.2.24 on 2025-11-04 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_adminorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaxuser',
            name='default_admin_organization',
            field=models.ForeignKey(blank=True, help_text='The default admin organization for the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.adminorganization'),
        ),
    ]
