# Generated by Django 5.2.8 on 2026-01-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_metaxuser_default_admin_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminorganization',
            name='allow_manual_rems_approval',
            field=models.BooleanField(default=False),
        ),
    ]
