# Generated by Django 5.2.11 on 2026-02-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_adminorganization_allow_manual_rems_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metaxuser',
            name='dac_organizations',
        ),
    ]
