# Generated by Django 5.2.13 on 2026-04-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_metaxuser_dac_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminorganization',
            name='dac_email',
            field=models.EmailField(blank=True, help_text='If set, REMS application related emails are sent to this address instead of individual handlers.', max_length=254, null=True),
        ),
    ]
