workflow:
  name: '$PIPELINE_NAME'
  rules:
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/
      variables:
        PIPELINE_NAME: 'Manual pipeline to $GITLAB_ENV'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        PIPELINE_NAME: 'MR pipeline'
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
      variables:
        PIPELINE_NAME: 'Commit pipeline'

# ------------------------

variables:
  GITLAB_ENV:
    description: 'Which environment do you want to deploy to?'
    value: 'rework' # switch back to test when rework-environment is deprecated
    options:
      #- 'demo'
      - 'rework'
      #- 'stable'
      - 'staging'
      #- 'test'

stages:
  - test
  - deploy
  - post-deploy

include:
  - project: fairdata/fairdata-ci
    ref: master
    file:
      - /templates/test/test-jobs.yaml
      - /templates/test/metax-v3-tests.yaml
      - /templates/deploy/metax-service-deploy-jobs.yaml

# ------------------------

unittests:
  stage: test
  extends: .metax-unittests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

sonarqube:
  extends: .sonarqube-job
  needs:
    - job: unittests
      artifacts: true
      optional: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

# ------------------------

prepare-service:
  extends: .prepare-service-play
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

prepare-service-feature:
  extends: .prepare-service-play
  variables:
    GITLAB_ENV: 'staging'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

deploy-service:
  extends: .deploy-service-play
  needs:
    - job: prepare-service
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

deploy-service-feature:
  extends: .deploy-service-play
  needs:
    - job: prepare-service-feature
  variables:
    GITLAB_ENV: 'staging'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# ------------------------

post-deployment-tasks:
  extends: .post-deployment-tasks-play
  needs:
    - job: deploy-service
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

post-deployment-tasks-feature:
  extends: .post-deployment-tasks-play
  needs:
    - job: deploy-service-feature
  variables:
    GITLAB_ENV: 'staging'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test-deployment:
  extends: .test-deployment-play
  needs:
    - job: deploy-service
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

test-deployment-feature:
  extends: .test-deployment-play
  needs:
    - job: deploy-service-feature
  variables:
    GITLAB_ENV: 'staging'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
