workflow:
  name: '$PIPELINE_NAME'
  rules:
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/
      variables:
        PIPELINE_NAME: 'Manual pipeline to $GITLAB_ENV'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        PIPELINE_NAME: 'MR pipeline'
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
      variables:
        PIPELINE_NAME: 'Commit pipeline'

# ------------------------

stages:
  - test
  - deploy
  - post-deploy

include:
  - project: fairdata/fairdata-ci
    ref: master
    file:
      - /templates/test/test-jobs.yaml
      - /templates/test/metax-v3-tests.yaml

# ------------------------

unittests:
  stage: test
  extends: .metax-unittests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

prepare-service:
  stage: deploy
  environment: $GITLAB_ENV
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY ${PLAYBOOKS_ROOT}/metax-service/v3/metax-deploy.yaml --vault-id $ANSIBLE_VAULT_FILE --tags "all-python-tasks,all-user-folder-tasks,all-os-packages-tasks"

deploy-service:
  stage: deploy
  environment: $GITLAB_ENV
  needs:
    - job: prepare-service
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY ${PLAYBOOKS_ROOT}/metax-service/v3/metax-deploy.yaml --vault-id $ANSIBLE_VAULT_FILE --tags "all-repository-tasks,all-pip-dependency-tasks,selected-django-tasks,django-migrate,collect-static,all-systemd-tasks,all-nginx-tasks"

test-deployment:
  stage: deploy
  environment: $GITLAB_ENV
  needs:
    - job: deploy-service
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY ${PLAYBOOKS_ROOT}/metax-service/v3/metax-deploy.yaml --vault-id $ANSIBLE_VAULT_FILE --tags "selected-django-tasks,run-unittests"

post-deployment-tasks:
  stage: deploy
  environment: $GITLAB_ENV
  needs:
    - job: deploy-service
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
  script:
    - ansible-playbook -i $ANSIBLE_INVENTORY ${PLAYBOOKS_ROOT}/metax-service/v3/metax-deploy.yaml --vault-id $ANSIBLE_VAULT_FILE --tags "selected-django-tasks,create-superusers,index-organizations,index-refdata"

sonarqube:
  extends: .sonarqube-job
  needs:
    - job: unittests
      artifacts: true
      optional: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/
