workflow:
  name: '$PIPELINE_NAME'
  rules:
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/
      variables:
        PIPELINE_NAME: 'Manual pipeline to $GITLAB_ENV'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        PIPELINE_NAME: 'MR pipeline'
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
      variables:
        PIPELINE_NAME: 'Commit pipeline'

# ------------------------

variables:
  GITLAB_ENV:
    description: 'Which environment do you want to deploy to?'
    value: 'staging'
    options:
      - 'staging'
      - 'test'
      - 'demo'
      - 'stable'

stages:
  - test
  - deploy
  - post-deploy

include:
  - project: fairdata/fairdata-ci
    ref: master
    file:
      - /templates/test/test-jobs.yaml
      - /templates/test/metax-v3-tests.yaml
      - /templates/deploy/metax-service-deploy-jobs.yaml


# ------------------------

unittests:
  stage: test
  extends: .metax-unittests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

prepare-service:
  extends: .prepare-service-play
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/

deploy-service:
  extends: .deploy-service-play
  needs:
    - job: prepare-service
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/

test-deployment:
  extends: .test-deployment-play
  needs:
    - job: deploy-service
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/

post-deployment-tasks:
  extends: .post-deployment-tasks-play
  needs:
    - job: deploy-service
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/

sonarqube:
  extends: .sonarqube-job
  needs:
    - job: unittests
      artifacts: true
      optional: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/
