---
stages:
  - test

include:
  - project: fairdata/fairdata-ci
    ref: master
    file:
      - /templates/test/test-jobs.yaml
      - /templates/test/metax-v3-tests.yaml

# ------------------------

unittests:
  stage: test
  extends: .metax-unittests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

sonarqube:
  extends: .sonarqube-job
  needs:
    - job: unittests
      artifacts: true
      optional: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/
