workflow:
  name: '$PIPELINE_NAME'
  rules:
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/
      variables:
        PIPELINE_NAME: 'Manual pipeline to $GITLAB_ENV'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        PIPELINE_NAME: 'MR pipeline'
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/
      variables:
        PIPELINE_NAME: 'Commit pipeline'

# ------------------------

variables:
  GITLAB_ENV:
    description: 'Which environment do you want to deploy to?'
    value: 'test'
    options:
      #- 'demo'
      - 'rework'
      #- 'stable'
      - 'staging'
      - 'test'

stages:
  - test
  - deploy
  - post-deploy

include:
  - project: fairdata/fairdata-ci
    ref: master
    file:
      - /templates/test/test-jobs.yaml
      - /templates/test/metax-v3-tests.yaml
      - /templates/deploy/metax-service-deploy-jobs.yaml

# ------------------------

unittests:
  stage: test
  extends: .metax-unittests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

sonarqube:
  stage: test
  extends: .sonarqube-job
  needs:
    - job: unittests
      artifacts: true
      optional: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

# ------------------------

# Deployment checks
# -----------------

prepare-service-staging:
  extends: .prepare-service-play
  variables:
    GITLAB_ENV: 'staging'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

deploy-service-staging:
  extends: .deploy-service-play
  needs:
    - job: prepare-service-staging
  variables:
    GITLAB_ENV: 'staging'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

post-deployment-tasks-staging:
  extends: .post-deployment-tasks-play
  stage: deploy
  needs:
    - job: deploy-service-staging
  variables:
    GITLAB_ENV: 'staging'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

test-deployment-staging:
  extends: .test-deployment-play
  stage: deploy
  needs:
    - job: post-deployment-tasks-staging
  variables:
    GITLAB_ENV: 'staging'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

# ------------------------

prepare-service:
  extends: .prepare-service-play
  variables:
    GITLAB_ENV: 'test'
  needs:
    - job: test-deployment-staging
      optional: true
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/


prepare-service-rework:
  extends: .prepare-service-play
  needs:
    - job: test-deployment-staging
  variables:
    GITLAB_ENV: 'rework'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

deploy-service:
  extends: .deploy-service-play
  needs:
    - job: prepare-service
  variables:
    GITLAB_ENV: 'test'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

deploy-service-rework:
  extends: .deploy-service-play
  needs:
    - job: prepare-service-rework
  variables:
    GITLAB_ENV: 'rework'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

# ------------------------

post-deployment-tasks:
  extends: .post-deployment-tasks-play
  needs:
    - job: deploy-service
  variables:
    GITLAB_ENV: 'test'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

post-deployment-tasks-rework:
  extends: .post-deployment-tasks-play
  needs:
    - job: deploy-service-rework
  variables:
    GITLAB_ENV: 'rework'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/

# ------------------------

test-deployment:
  extends: .test-deployment-play
  needs:
    - job: post-deployment-tasks
  variables:
    GITLAB_ENV: 'test'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/
    - if: $CI_PIPELINE_SOURCE =~ /^(web)$/

test-deployment-rework:
  extends: .test-deployment-play
  needs:
    - job: post-deployment-tasks-rework
  variables:
    GITLAB_ENV: 'rework'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master)$/ && $CI_PIPELINE_SOURCE !~ /^(web)$/
