site_name: Fairdata Metax Docs

theme:
  name: "material"
extra_css: [extra.css]
watch:
- src/apps
- tests/
plugins:
- search
- mkdocstrings:
    default_handler: python
- literate-nav:
    nav_file: SUMMARY.md
- section-index
markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes
