site_name: Fairdata Metax Docs

theme:
  name: "material"
plugins:
- search
- mkdocstrings:
    watch:
    - src/apps
    - tests/
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- print-site:
    add_to_navigation: true
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
