site_name: Fairdata Metax Docs

theme:
  name: "material"

nav:
- Home: index.md
- 'Reference':
    - 'Django Models': reference/django-models.md
    - 'Django Views' : reference/django-views.md
    - 'Django Serializers' : reference/django-serializers.md
    - 'Unit Tests' : reference/unit-tests.md
- 'Developer Guide':
    - 'Installation': developer-guide/install.md
    - 'Dependencies': developer-guide/dependencies-index.md
    - 'Managing Dependencies': developer-guide/dependencies.md
- 'User Guide':
    - 'Quick Start': user-guide/quickstart.md

plugins:
- search
- mkdocstrings:
    watch:
    - src/apps
- section-index
