site_name: Fairdata Metax Documentation
site_url: https://metaxv3.fd-dev.csc.fi/docs
theme:
  name: "material"
  features:
    - content.tabs.link
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
  logo: tree_nega_cropped.svg
  favicon: favicon.png
  palette: 
    primary: custom
    accent: custom
extra_css: [extra.css]
extra_javascript:
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- javascripts/tablesort.js
watch:
- src/apps
- tests/
plugins:
- search
- mkdocstrings:
    default_handler: python
- literate-nav:
    nav_file: SUMMARY.md
- section-index
markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: '#'
  - footnotes
  - md_in_html
  - tables
