# Generated by Django 3.2.21 on 2023-10-19 14:58
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
    ]
