# Generated by Django 3.2.12 on 2022-03-02 09:32

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        HStoreExtension(),
    ]
