# Generated by Django 3.2.22 on 2023-10-26 15:13

import apps.core.models.concepts
from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0002_auto_20231026_1513'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_squashed_0026_auto_20231019_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='example: {"en":"title", "fi":"otsikko"}', null=True)),
                ('description', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='example: {"en":"description", "fi":"kuvaus"}', null=True)),
                ('entity_identifier', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.relationtype'),
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.resourcetype'),
        ),
        migrations.CreateModel(
            name='RestrictionGrounds',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.restrictiongrounds'),
        ),
        migrations.AlterField(
            model_name='accessrights',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_accessrightss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cataloghomepage',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_cataloghomepages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='catalogrecord',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_catalogrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datacatalog',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_datacatalogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='example: {"en":"description", "fi":"kuvaus"}', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='issued',
            field=models.DateField(blank=True, help_text='Date of formal issuance (e.g., publication) of the resource.', null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='other_versions',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='_core_dataset_other_versions_+', to='core.Dataset'),
        ),
        migrations.AlterField(
            model_name='datasetlicense',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_datasetlicenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasetproject',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_datasetprojects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasetpublisher',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_datasetpublishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_filesets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalaccessrights',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcataloghomepage',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcatalogrecord',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldatacatalog',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldataset',
            name='description',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='example: {"en":"description", "fi":"kuvaus"}', null=True),
        ),
        migrations.AlterField(
            model_name='historicaldataset',
            name='issued',
            field=models.DateField(blank=True, help_text='Date of formal issuance (e.g., publication) of the resource.', null=True),
        ),
        migrations.AlterField(
            model_name='historicaldataset',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldatasetpublisher',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metadataprovider',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_metadataproviders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otheridentifier',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_otheridentifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcontributor',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_projectcontributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_provenances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provenancevariable',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_provenancevariables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remoteresource',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_remoteresources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spatial',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_spatials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temporal',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_temporals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AccessRightsRestrictionGrounds',
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='core.entity'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.relationtype'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_entityrelations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_entity', to='core.provenance'),
        ),
        migrations.AddField(
            model_name='entity',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_entitys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.resourcetype'),
        ),
        migrations.AddField(
            model_name='accessrights',
            name='restriction_grounds',
            field=models.ManyToManyField(related_name='access_rights', to='core.RestrictionGrounds'),
        ),
    ]
