# Generated by Django 3.2.16 on 2022-12-19 07:09

import apps.core.helpers
import apps.core.models.concepts
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refdata', '0002_auto_20221219_0909'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRights',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='example: {"en":"description", "fi":"kuvaus"}', null=True)),
            ],
            options={
                'verbose_name_plural': 'Access rights',
            },
        ),
        migrations.CreateModel(
            name='CatalogHomePage',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='valid url to the property definition', max_length=512)),
                ('title', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('system_creator', models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_cataloghomepages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogRecord',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataStorage',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(help_text='A unique id of the data storage', max_length=255, primary_key=True, serialize=False)),
                ('endpoint_url', models.URLField(help_text='The root location or primary endpoint of the service (a Web-resolvable IRI).')),
                ('endpoint_description', models.TextField(help_text='A description of the services available via the end-points, including their operations, parameters etc.')),
                ('system_creator', models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_datastorages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.accesstype'),
        ),
        migrations.CreateModel(
            name='FieldOfScience',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.fieldofscience'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.language'),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.license'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.theme'),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('catalogrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.catalogrecord')),
                ('persistent_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('issued', models.DateTimeField(blank=True, help_text='Date of formal issuance (e.g., publication) of the resource.', null=True)),
                ('title', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('description', django.contrib.postgres.fields.hstore.HStoreField(blank=True, max_length=255, null=True)),
                ('keyword', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('other_identifiers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('cumulation_started', models.DateTimeField(blank=True, null=True)),
                ('cumulation_ended', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('core.catalogrecord', models.Model),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('checksum', models.TextField()),
                ('date_frozen', models.DateTimeField(blank=True, null=True)),
                ('file_format', models.CharField(max_length=200, null=True)),
                ('file_name', models.TextField()),
                ('file_path', models.TextField()),
                ('date_uploaded', models.DateTimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('system_creator', models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetPublisher',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en": "name", "fi":"nimi"}')),
                ('homepage', models.ManyToManyField(related_name='publishers', to='core.CatalogHomePage')),
                ('system_creator', models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_datasetpublishers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataCatalog',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(help_text='A unique id of the resource being described or cataloged.', max_length=255, primary_key=True, serialize=False)),
                ('title', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('dataset_versioning_enabled', models.BooleanField(default=False)),
                ('harvested', models.BooleanField(default=False)),
                ('dataset_schema', models.CharField(choices=[('ida', 'IDA Schema'), ('att', 'ATT Schema'), ('drf', 'DRF Schema')], default='ida', max_length=6)),
                ('access_rights', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', to='core.accessrights')),
                ('language', models.ManyToManyField(related_name='catalogs', to='core.Language')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', to='core.datasetpublisher')),
                ('system_creator', models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_datacatalogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='valid url to the property definition', max_length=512)),
                ('title', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('quota', models.BigIntegerField()),
                ('valid_until', models.DateTimeField()),
                ('system_creator', models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='catalogrecord',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.contract'),
        ),
        migrations.AddField(
            model_name='catalogrecord',
            name='data_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='core.datacatalog'),
        ),
        migrations.AddField(
            model_name='catalogrecord',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_catalogrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrights',
            name='access_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_rights', to='core.accesstype'),
        ),
        migrations.AddField(
            model_name='accessrights',
            name='license',
            field=models.ManyToManyField(related_name='access_rights', to='core.License'),
        ),
        migrations.AddField(
            model_name='accessrights',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_accessrightss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(help_text='A specific representation of a dataset.', max_length=255, primary_key=True, serialize=False)),
                ('title', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('issued', models.DateTimeField(blank=True, help_text='Date of formal issuance (e.g., publication) of the resource.', null=True)),
                ('access_url', models.URLField()),
                ('download_url', models.URLField()),
                ('byte_size', models.BigIntegerField(default=0)),
                ('checksum', models.TextField()),
                ('access_rights', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='core.accessrights')),
                ('access_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='core.datastorage')),
                ('files', models.ManyToManyField(related_query_name='distributions', to='core.File')),
                ('license', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='core.license')),
                ('system_creator', models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_distributions', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='core.dataset')),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='access_rights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='core.accessrights'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='field_of_science',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='core.FieldOfScience'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='first',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_version', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='core.Language'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='last',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_version', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='core.Theme'),
        ),
    ]
