# Generated by Django 3.2.12 on 2022-03-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetlicense',
            name='license',
        ),
    ]
