# Generated by Django 3.2.18 on 2023-04-26 11:57

from django.db import migrations

def generate_other_license(apps, schema_editor):
    License = apps.get_model("refdata", "License")
    License.objects.get_or_create(
        url="http://uri.suomi.fi/codelist/fairdata/license/code/other",
        defaults={
            "pref_label": {"en": "Other", "fi": "Muu"},
            "in_scheme": "http://uri.suomi.fi/codelist/fairdata/license"})

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('refdata', '0005_auto_20230315_1529'),
    ]

    operations = [
        migrations.RunPython(generate_other_license, migrations.RunPython.noop),
    ]
