# Generated by Django 3.2.22 on 2023-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231026_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
