# Generated by Django 3.2.15 on 2022-08-11 07:06

import apps.core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20220810_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessright',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesstype',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cataloghomepage',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalogrecord',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datacatalog',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasetlanguage',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasetlicense',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasetpublisher',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datastorage',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distribution',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
