# Generated by Django 3.2.16 on 2023-01-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230119_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogrecord',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='preservation_state',
        ),
        migrations.RemoveField(
            model_name='historicalcatalogrecord',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='historicaldataset',
            name='last_modified_by',
        ),
        migrations.AddField(
            model_name='catalogrecord',
            name='preservation_state',
            field=models.IntegerField(choices=[(0, 'Initialized'), (10, 'Proposed'), (20, 'Technical Metadata Generated'), (30, 'Technical Metadata Generated Failed'), (40, 'Invalid Metadata'), (50, 'Metadata Validation Failed'), (60, 'Validated Metadata Updated'), (65, 'Validating Metadata'), (70, 'Valid Metadata'), (75, 'Metadata Confirmed'), (80, 'Accepted To Pas'), (90, 'In Packaging Service'), (100, 'Packaging Failed'), (110, 'Sip In Ingestion'), (120, 'In Pas'), (130, 'Rejected From Pas'), (140, 'In Dissemination')], default=0, help_text='Record state in PAS.'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='cumulative_state',
            field=models.IntegerField(choices=[(0, 'Not cumulative'), (1, 'Active'), (2, 'Closed')], default=0, help_text='Cumulative state'),
        ),
        migrations.AddField(
            model_name='historicalcatalogrecord',
            name='preservation_state',
            field=models.IntegerField(choices=[(0, 'Initialized'), (10, 'Proposed'), (20, 'Technical Metadata Generated'), (30, 'Technical Metadata Generated Failed'), (40, 'Invalid Metadata'), (50, 'Metadata Validation Failed'), (60, 'Validated Metadata Updated'), (65, 'Validating Metadata'), (70, 'Valid Metadata'), (75, 'Metadata Confirmed'), (80, 'Accepted To Pas'), (90, 'In Packaging Service'), (100, 'Packaging Failed'), (110, 'Sip In Ingestion'), (120, 'In Pas'), (130, 'Rejected From Pas'), (140, 'In Dissemination')], default=0, help_text='Record state in PAS.'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='cumulative_state',
            field=models.IntegerField(choices=[(0, 'Not cumulative'), (1, 'Active'), (2, 'Closed')], default=0, help_text='Cumulative state'),
        ),
        migrations.AddField(
            model_name='spatial',
            name='altitude_in_meters',
            field=models.IntegerField(blank=True, help_text='The altitude of the geographical area (meters from WGS84 reference)', null=True),
        ),
    ]
