# Generated by Django 3.2.18 on 2023-05-12 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_auto_20230421_1011'),
        ('core', '0003_auto_20230426_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetDirectoryMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_path', models.TextField(db_index=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='directory_metadata', to='core.dataset')),
                ('file_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.filestorage')),
                ('use_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usecategory')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetFileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_metadata', to='core.dataset')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_metadata', to='files.file')),
                ('file_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filetype')),
                ('use_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usecategory')),
            ],
            options={
                'unique_together': {('dataset', 'file')},
            },
        ),
    ]
