# Generated by Django 3.2.22 on 2023-10-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231026_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogrecord',
            name='data_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='core.datacatalog'),
        ),
    ]
