# Generated by Django 3.2.12 on 2022-04-13 08:22

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_datastorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('checksum', models.TextField()),
                ('date_frozen', models.DateTimeField(blank=True, null=True)),
                ('file_format', models.CharField(max_length=200, null=True)),
                ('file_name', models.TextField()),
                ('file_path', models.TextField()),
                ('date_uploaded', models.DateTimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('file_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.datastorage')),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.URLField(help_text='valid url to the property definition', max_length=512, primary_key=True, serialize=False)),
                ('title', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('access_url', models.URLField()),
                ('download_url', models.URLField()),
                ('byte_size', models.BigIntegerField(default=0)),
                ('checksum', models.TextField()),
                ('access_rights', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='core.accessright')),
                ('access_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='core.datastorage')),
                ('files', models.ManyToManyField(related_query_name='distributions', to='core.File')),
                ('license', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='core.datasetlicense')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
