# Generated by Django 3.2.18 on 2023-05-26 10:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_datasetdirectorymetadata_datasetfilemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatial',
            name='custom_wkt',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, help_text='Additional wkt values according to WGS84', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='spatial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance', to='core.spatial'),
        ),
    ]
