# Generated by Django 3.2.15 on 2022-08-11 10:32

import apps.core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20220811_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
