# Generated by Django 4.2.11 on 2024-03-26 12:37

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dataset_data_catalog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrights',
            options={'ordering': ['created', 'id']},
        ),
        migrations.AlterModelOptions(
            name='datasetactor',
            options={'ordering': ['actors_order', 'created', 'id']},
        ),
        migrations.AlterModelOptions(
            name='historicalaccessrights',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical access rights', 'verbose_name_plural': 'historical access rightss'},
        ),
        migrations.AddField(
            model_name='legacydataset',
            name='last_successful_migration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legacydataset',
            name='migration_errors',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
