# Generated by Django 3.2.12 on 2022-05-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_distribution_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetlicense',
            name='license',
        ),
    ]
