# Generated by Django 3.2.15 on 2022-11-07 08:39

import apps.core.helpers
import apps.core.models.concepts
from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20220905_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRights',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='example: {"en":"description", "fi":"kuvaus"}', null=True)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='accessright',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='accessright',
            name='license',
        ),
        migrations.RemoveField(
            model_name='accessright',
            name='system_creator',
        ),
        migrations.RemoveField(
            model_name='datasetlanguage',
            name='system_creator',
        ),
        migrations.RemoveField(
            model_name='datasetlicense',
            name='system_creator',
        ),
        migrations.CreateModel(
            name='FieldOfScience',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.fieldofscience'),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.keyword'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.language'),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.license'),
        ),
        migrations.AlterModelOptions(
            name='researchdataset',
            options={'get_latest_by': 'modified', 'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='researchdataset',
            name='access_right',
        ),
        migrations.RemoveField(
            model_name='researchdataset',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='researchdataset',
            name='url',
        ),
        migrations.AddField(
            model_name='distribution',
            name='issued',
            field=models.DateTimeField(blank=True, help_text='Date of formal issuance (e.g., publication) of the resource.', null=True),
        ),
        migrations.AddField(
            model_name='researchdataset',
            name='issued',
            field=models.DateTimeField(blank=True, help_text='Date of formal issuance (e.g., publication) of the resource.', null=True),
        ),
        migrations.AlterField(
            model_name='researchdataset',
            name='description',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AccessType',
        ),
        migrations.AddField(
            model_name='accessrights',
            name='license',
            field=models.ManyToManyField(related_name='access_rights', to='core.License'),
        ),
        migrations.AddField(
            model_name='accessrights',
            name='system_creator',
            field=models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_accessrightss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchdataset',
            name='access_rights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_datasets', to='core.accessrights'),
        ),
        migrations.AddField(
            model_name='researchdataset',
            name='field_of_science',
            field=models.ManyToManyField(blank=True, related_name='research_datasets', to='core.FieldOfScience'),
        ),
        migrations.AddField(
            model_name='researchdataset',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='research_datasets', to='core.Keyword'),
        ),
        migrations.AlterField(
            model_name='datacatalog',
            name='access_rights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', to='core.accessrights'),
        ),
        migrations.RemoveField(
            model_name='datacatalog',
            name='language',
        ),
        migrations.AlterField(
            model_name='distribution',
            name='access_rights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='core.accessrights'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='core.license'),
        ),
        migrations.RemoveField(
            model_name='researchdataset',
            name='language',
        ),
        migrations.DeleteModel(
            name='AccessRight',
        ),
        migrations.DeleteModel(
            name='DatasetLicense',
        ),
        migrations.CreateModel(
            name='AccessType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.accesstype'),
        ),
        migrations.AddField(
            model_name='accessrights',
            name='access_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_rights', to='core.accesstype'),
        ),
    ]
