# Generated by Django 3.2.16 on 2023-02-08 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20230208_0959'),
        ('core', '0006_auto_20230123_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastorage',
            name='system_creator',
        ),
        migrations.RemoveField(
            model_name='file',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='file',
            name='system_creator',
        ),
        migrations.RemoveField(
            model_name='historicaldatastorage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldatastorage',
            name='system_creator',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='system_creator',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='files',
            field=models.ManyToManyField(related_name='datasets', to='files.File'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='access_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='files.filestorage'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='files',
            field=models.ManyToManyField(related_query_name='distributions', to='files.File'),
        ),
        migrations.AlterField(
            model_name='historicaldistribution',
            name='access_service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='files.filestorage'),
        ),
        migrations.AlterField(
            model_name='historicaldistribution_files',
            name='file',
            field=models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='files.file'),
        ),
        migrations.DeleteModel(
            name='Checksum',
        ),
        migrations.DeleteModel(
            name='DataStorage',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='HistoricalDataStorage',
        ),
        migrations.DeleteModel(
            name='HistoricalFile',
        ),
    ]
