# Generated by Django 3.2.21 on 2023-10-10 12:29

from django.db import migrations
from django.db.models import Q


def migrate_to_model(apps, schema_editor):
    """Copy preservation fields to new Preservation model"""
    Dataset = apps.get_model("core", "Dataset")
    Preservation = apps.get_model("core", "Preservation")

    datasets = Dataset.objects.filter(
        Q(preservation_state__gt=-1)
        | Q(contract__isnull=False)
        | Q(preservation_identifier__isnull=False)
    )

    for dataset in datasets:
        dataset.preservation, _ = Preservation.objects.update_or_create(
            id=dataset.preservation_identifier,
            defaults={
                "state": dataset.preservation_state,
                "contract_id": dataset.contract_id
            }
        )
        dataset.save()


def migrate_from_model(apps, schema_editor):
    """Copy preservation fields back from new Preservation model"""
    Dataset = apps.get_model("core", "Dataset")

    datasets = (
        Dataset.objects
            .filter(preservation_id__isnull=False)
            .select_related("preservation")
    )

    for dataset in datasets:
        dataset.preservation_state = dataset.preservation.state
        dataset.contract = dataset.preservation.contract
        dataset.preservation_identifier = dataset.preservation.id
        dataset.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_preservation'),
    ]

    operations = [
        migrations.RunPython(migrate_to_model, migrate_from_model)
    ]
