# Generated by Django 3.2.15 on 2022-11-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221107_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasetLanguage',
        ),
        migrations.AddField(
            model_name='datacatalog',
            name='language',
            field=models.ManyToManyField(related_name='catalogs', to='core.Language'),
        ),
        migrations.AddField(
            model_name='researchdataset',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='research_datasets', to='core.Language'),
        ),
    ]
