# Generated by Django 3.2.16 on 2023-02-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230208_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldistribution',
            name='access_rights',
        ),
        migrations.RemoveField(
            model_name='historicaldistribution',
            name='access_service',
        ),
        migrations.RemoveField(
            model_name='historicaldistribution',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='historicaldistribution',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldistribution',
            name='license',
        ),
        migrations.RemoveField(
            model_name='historicaldistribution',
            name='system_creator',
        ),
        migrations.RemoveField(
            model_name='historicaldistribution_files',
            name='distribution',
        ),
        migrations.RemoveField(
            model_name='historicaldistribution_files',
            name='file',
        ),
        migrations.RemoveField(
            model_name='historicaldistribution_files',
            name='history',
        ),
        migrations.DeleteModel(
            name='Distribution',
        ),
        migrations.DeleteModel(
            name='HistoricalDistribution',
        ),
        migrations.DeleteModel(
            name='HistoricalDistribution_files',
        ),
    ]
