# Generated by Django 3.2.22 on 2023-11-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_move_preservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogrecord',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='catalogrecord',
            name='preservation_identifier',
        ),
        migrations.RemoveField(
            model_name='catalogrecord',
            name='preservation_state',
        ),
        migrations.RemoveField(
            model_name='historicalcatalogrecord',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='historicalcatalogrecord',
            name='preservation_identifier',
        ),
        migrations.RemoveField(
            model_name='historicalcatalogrecord',
            name='preservation_state',
        ),
        migrations.RemoveField(
            model_name='historicaldataset',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='historicaldataset',
            name='preservation_identifier',
        ),
        migrations.RemoveField(
            model_name='historicaldataset',
            name='preservation_state',
        ),
    ]
