# Generated by Django 4.2.11 on 2024-03-27 12:25

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_legacydataset_ignored_legacy_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetlicense',
            name='title',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='example: {"en":"title", "fi":"otsikko"}', null=True),
        ),
        migrations.AlterField(
            model_name='datasetlicense',
            name='description',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='example: {"en":"description", "fi":"kuvaus"}', null=True),
        ),
    ]
