# Generated by Django 3.2.15 on 2022-11-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221107_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrights',
            options={'verbose_name_plural': 'Access rights'},
        ),
    ]
