# Generated by Django 3.2.22 on 2023-11-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_old_preservation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogrecord',
            name='metadata_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.metadataprovider'),
        ),
    ]
