# Generated by Django 4.2.11 on 2024-03-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_legacydataset_fixed_legacy_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legacydataset',
            old_name='ignored_legacy_values',
            new_name='invalid_legacy_values',
        ),
    ]
