# Generated by Django 3.2.22 on 2023-11-28 09:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_catalogrecord_metadata_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetactor',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='core.dataset'),
        ),
        migrations.AlterField(
            model_name='datasetactor',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('creator', 'Creator'), ('contributor', 'Contributor'), ('publisher', 'Publisher'), ('curator', 'Curator'), ('rights_holder', 'Rights holder')], default='creator', max_length=30), blank=True, default=list, size=None),
        ),
    ]
