# Generated by Django 3.2.15 on 2022-11-10 10:39

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_accessrights_options'),
    ]

    operations = [
        migrations.RenameModel('ResearchDataset', 'Dataset')
    ]
