# Generated by Django 3.2.18 on 2023-05-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_dataset_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otheridentifier',
            name='dataset',
        ),
        migrations.AddField(
            model_name='dataset',
            name='other_identifier',
            field=models.ManyToManyField(blank=True, to='core.OtherIdentifier'),
        ),
        migrations.AlterField(
            model_name='otheridentifier',
            name='identifier_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_identifiers', to='core.identifiertype'),
        ),
        migrations.AddField(
            model_name='otheridentifier',
            name='old_notation',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='other_identifier',
            new_name='other_identifiers',
        ),
    ]
