# Generated by Django 3.2.22 on 2023-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_catalogrecord_metadata_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='pid_type',
            field=models.CharField(blank=True, choices=[('URN', 'URN'), ('DOI', 'DOI')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='pid_type',
            field=models.CharField(blank=True, choices=[('URN', 'URN'), ('DOI', 'DOI')], max_length=4, null=True),
        ),
    ]
