# Generated by Django 3.2.18 on 2023-03-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dataset_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='field_of_science',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_essential_choice': True}, related_name='datasets', to='core.FieldOfScience'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='theme',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_essential_choice': True}, related_name='datasets', to='core.Theme'),
        ),
    ]
