# Generated by Django 3.2.19 on 2023-06-30 07:35

import apps.core.models.concepts
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_person'),
        ('refdata', '0009_alter_location_as_wkt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20230526_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.contributortype'),
        ),
        migrations.RemoveField(
            model_name='datasetproject',
            name='funding_agency',
        ),
        migrations.RemoveField(
            model_name='datasetproject',
            name='participating_organization',
        ),
        migrations.CreateModel(
            name='ProjectContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_project', to='actors.actor')),
                ('contribution_type', models.ManyToManyField(related_name='projects', to='refdata.ContributorType')),
                ('participating_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='actors.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='core.datasetproject')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_projectcontributors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datasetproject',
            name='funding_agency',
            field=models.ManyToManyField(related_name='is_funding', to='core.ProjectContributor'),
        ),
        migrations.AddField(
            model_name='datasetproject',
            name='participating_organization',
            field=models.ManyToManyField(related_name='is_participating', to='core.ProjectContributor'),
        ),
    ]
