# Generated by Django 3.2.22 on 2023-12-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20231128_0937'),
        ('core', '0010_auto_20231204_0547'),
    ]

    operations = [
    ]
