# Generated by Django 3.2.22 on 2023-12-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_merge_0010_auto_20231128_0937_0010_auto_20231204_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetactor',
            options={'ordering': ['actors_order', 'created']},
        ),
        migrations.AddField(
            model_name='datasetactor',
            name='actors_order',
            field=models.IntegerField(default=0, help_text='Position in dataset actors list.'),
        ),
    ]
