# Generated by Django 3.2.15 on 2022-11-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_research_dataset_schema_datacatalog_dataset_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='access_rights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='core.accessrights'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='field_of_science',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='core.FieldOfScience'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='core.Language'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='core.Keyword'),
        ),
    ]
