# Generated by Django 4.2.11 on 2024-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dataset_bibliographic_citation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatial',
            name='altitude_in_meters',
            field=models.FloatField(blank=True, help_text='The altitude of the geographical area (meters from WGS84 reference)', null=True),
        ),
    ]
