# Generated by Django 4.2.11 on 2024-04-09 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_spatial_altitude_in_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='funder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding', to='core.funder'),
        ),
    ]
