# Generated by Django 3.2.22 on 2023-12-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20231213_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='is_deprecated',
        ),
        migrations.RemoveField(
            model_name='historicaldataset',
            name='is_deprecated',
        ),
        migrations.AddField(
            model_name='dataset',
            name='deprecated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='deprecated',
            field=models.DateTimeField(null=True),
        ),
    ]
