# Generated by Django 3.2.22 on 2023-12-20 08:25

import apps.core.models.concepts
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0002_auto_20231026_1513'),
        ('core', '0013_auto_20231219_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservationEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.preservationevent'),
        ),
        migrations.AddField(
            model_name='provenance',
            name='preservation_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.preservationevent'),
        ),
    ]
