# Generated by Django 3.2.19 on 2023-08-14 15:11

import apps.core.models.concepts
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0009_alter_location_as_wkt'),
        ('core', '0013_alter_provenance_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.license'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.location'),
        ),
    ]
