# Generated by Django 3.2.22 on 2024-01-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20240102_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacatalog',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatacatalog',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
