# Generated by Django 4.2.11 on 2024-05-29 08:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_datacatalog_dataset_schema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legacydataset',
            name='files_json',
        ),
        migrations.AddField(
            model_name='legacydataset',
            name='legacy_file_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None),
        ),
    ]
