# Generated by Django 4.2.11 on 2024-07-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_datacatalog_dataset_schema_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrights',
            options={'ordering': ['created', 'id'], 'verbose_name_plural': 'Access rights'},
        ),
        migrations.AlterModelOptions(
            name='historicalaccessrights',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical access rights', 'verbose_name_plural': 'historical Access rights'},
        ),
        migrations.AlterField(
            model_name='dataset',
            name='field_of_science',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='core.fieldofscience'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='core.language'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='core.theme'),
        ),
    ]
