# Generated by Django 3.2.22 on 2024-01-23 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20240122_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='draft_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_draft', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='draft_of',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.dataset'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='access_rights',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset', to='core.accessrights'),
        ),
    ]
