# Generated by Django 3.2.19 on 2023-08-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230822_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileset',
            old_name='file_storage',
            new_name='storage',
        ),
        migrations.RenameField(
            model_name='filesetdirectorymetadata',
            old_name='directory_path',
            new_name='pathname',
        ),
        migrations.RenameField(
            model_name='filesetdirectorymetadata',
            old_name='file_storage',
            new_name='storage',
        ),
        migrations.AlterUniqueTogether(
            name='filesetdirectorymetadata',
            unique_together={('file_set', 'pathname')},
        ),
    ]
