# Generated by Django 3.2.20 on 2023-09-15 06:29

import apps.core.models.concepts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0009_alter_location_as_wkt'),
        ('core', '0019_auto_20230908_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchInfra',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.core.models.concepts.ConceptProxyMixin, 'refdata.researchinfra'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='infrastructure',
            field=models.ManyToManyField(blank=True, related_name='datasets', to='core.ResearchInfra'),
        ),
    ]
