# Generated by Django 3.2.21 on 2023-09-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230919_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='published_version',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='published_version',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
