# Generated by Django 4.2.11 on 2024-06-14 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_datasetpermissions_historicaldatasetpermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetMetrics',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('downloads_complete_failed', models.IntegerField(blank=True, default=0)),
                ('downloads_complete_successful', models.IntegerField(blank=True, default=0)),
                ('downloads_file_failed', models.IntegerField(blank=True, default=0)),
                ('downloads_file_successful', models.IntegerField(blank=True, default=0)),
                ('downloads_package_failed', models.IntegerField(blank=True, default=0)),
                ('downloads_package_successful', models.IntegerField(blank=True, default=0)),
                ('downloads_partial_failed', models.IntegerField(blank=True, default=0)),
                ('downloads_partial_successful', models.IntegerField(blank=True, default=0)),
                ('downloads_total_failed', models.IntegerField(blank=True, default=0)),
                ('downloads_total_requests', models.IntegerField(blank=True, default=0)),
                ('downloads_total_successful', models.IntegerField(blank=True, default=0)),
                ('views_data_views', models.IntegerField(blank=True, default=0)),
                ('views_details_views', models.IntegerField(blank=True, default=0)),
                ('views_events_views', models.IntegerField(blank=True, default=0)),
                ('views_maps_views', models.IntegerField(blank=True, default=0)),
                ('views_total_views', models.IntegerField(blank=True, default=0)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.dataset')),
                ('system_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created', 'id'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
