# Generated by Django 3.2.22 on 2024-02-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0020_auto_20240212_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacatalog',
            name='dataset_groups_admin',
            field=models.ManyToManyField(blank=True, help_text='User groups that are allowed to update all datasets in catalog.', related_name='catalogs_admin_datasets', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='datacatalog',
            name='dataset_groups_create',
            field=models.ManyToManyField(blank=True, help_text='User groups that are allowed to create datasets in catalog.', related_name='catalogs_create_datasets', to='auth.Group'),
        ),
    ]
