# Generated by Django 4.2.11 on 2024-07-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_datasetmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetpermissions',
            name='legacy_modified',
            field=models.DateTimeField(blank=True, help_text='Latest modification from legacy Metax.', null=True),
        ),
        migrations.AddField(
            model_name='historicaldatasetpermissions',
            name='legacy_modified',
            field=models.DateTimeField(blank=True, help_text='Latest modification from legacy Metax.', null=True),
        ),
    ]
