# Generated by Django 3.2.21 on 2023-09-28 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_remoteresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrights',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_accessrightss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accessrightsrestrictiongrounds',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_accessrightsrestrictiongroundss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cataloghomepage',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_cataloghomepages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='catalogrecord',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_catalogrecords', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datacatalog',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_datacatalogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasetlicense',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_datasetlicenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasetproject',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_datasetprojects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datasetpublisher',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_datasetpublishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileset',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_filesets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalaccessrights',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcataloghomepage',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcatalogrecord',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldatacatalog',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldataset',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaldatasetpublisher',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metadataprovider',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_metadataproviders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otheridentifier',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_otheridentifiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcontributor',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_projectcontributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provenance',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_provenances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provenancevariable',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_provenancevariables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remoteresource',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_remoteresources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spatial',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_spatials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temporal',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_temporals', to=settings.AUTH_USER_MODEL),
        ),
    ]
