# Generated by Django 4.2.15 on 2024-09-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_accessrights_options_and_more'),
        ('core', '0021_datasetpermissions_legacy_modified_and_more'),
    ]

    operations = [
    ]
