# Generated by Django 4.2.11 on 2024-09-09 07:19

import django.contrib.postgres.fields
from django.db import migrations, models

from apps.core.models.legacy_versions import migrate_dataset_versions

def assign_versions(apps, schema_editor):
    migrate_dataset_versions(apps=apps)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_datasetpermissions_legacy_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversions',
            name='legacy_versions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
        migrations.RunPython(assign_versions, migrations.RunPython.noop),
    ]
