# Generated by Django 3.2.21 on 2023-10-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230928_1442'),
        ('core', '0023_auto_20231011_1401'),
    ]

    operations = [
    ]
