# Generated by Django 4.2.11 on 2024-10-02 09:06

import apps.core.models.data_catalog
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_dataset_record_created_dataset_record_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacatalog',
            name='publishing_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('etsin', 'etsin'), ('ttv', 'ttv')], max_length=64), blank=True, default=apps.core.models.data_catalog.default_publishing_channels, help_text='Channels in which datasets in this catalog will be published.', size=None),
        ),
        migrations.AddField(
            model_name='historicaldatacatalog',
            name='publishing_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('etsin', 'etsin'), ('ttv', 'ttv')], max_length=64), blank=True, default=apps.core.models.data_catalog.default_publishing_channels, help_text='Channels in which datasets in this catalog will be published.', size=None),
        ),
    ]
