# Generated by Django 4.2.11 on 2024-03-18 14:21

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_alter_accessrights_system_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provenancevariable',
            name='in_scheme',
        ),
        migrations.RemoveField(
            model_name='provenancevariable',
            name='title',
        ),
        migrations.RemoveField(
            model_name='provenancevariable',
            name='url',
        ),
        migrations.RemoveField(
            model_name='spatial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spatial',
            name='in_scheme',
        ),
        migrations.RemoveField(
            model_name='spatial',
            name='pref_label',
        ),
        migrations.RemoveField(
            model_name='spatial',
            name='representation',
        ),
        migrations.RemoveField(
            model_name='spatial',
            name='title',
        ),
        migrations.RemoveField(
            model_name='spatial',
            name='url',
        ),
        migrations.AlterField(
            model_name='provenance',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenance', to='core.dataset'),
        ),
        migrations.AlterField(
            model_name='provenancevariable',
            name='description',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='example: {"en":"This variable indicates the person\'s age in years"}', null=True),
        ),
        migrations.AlterField(
            model_name='provenancevariable',
            name='pref_label',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={'en': 'Variable'}, help_text='example: {"en":"Age"}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provenancevariable',
            name='provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='core.provenance'),
        ),
        migrations.AlterField(
            model_name='provenancevariable',
            name='representation',
            field=models.URLField(blank=True, help_text='Scheme that contains the possible values of the variable.', null=True),
        ),
        migrations.CreateModel(
            name='VariableUniverse',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='The preferred label of the concept.', null=True)),
                ('definition', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Definition or formal explanation of the concept.', null=True)),
                ('concept_identifier', models.URLField(help_text='An URL identifying the concept.', max_length=512)),
                ('in_scheme', models.URLField(blank=True, help_text='The scheme the concept belongs to.', max_length=255, null=True)),
                ('system_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created', 'id'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableConcept',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='The preferred label of the concept.', null=True)),
                ('definition', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Definition or formal explanation of the concept.', null=True)),
                ('concept_identifier', models.URLField(help_text='An URL identifying the concept.', max_length=512)),
                ('in_scheme', models.URLField(blank=True, help_text='The scheme the concept belongs to.', max_length=255, null=True)),
                ('system_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created', 'id'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='provenancevariable',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.variableconcept'),
        ),
        migrations.AddField(
            model_name='provenancevariable',
            name='universe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.variableuniverse'),
        ),
    ]
