# Generated by Django 3.2.22 on 2023-10-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_dataset_other_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='issued',
            field=models.DateField(blank=True, help_text='Date of formal issuance (e.g., publication) of the resource.', null=True),
        ),
        migrations.AlterField(
            model_name='historicaldataset',
            name='issued',
            field=models.DateField(blank=True, help_text='Date of formal issuance (e.g., publication) of the resource.', null=True),
        ),
        migrations.AlterField(
            model_name='temporal',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
