# Generated by Django 4.2.16 on 2024-10-07 12:21

import apps.core.models.data_catalog
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_pid_type_dataset_generate_pid_on_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacatalog',
            name='allowed_pid_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('URN', 'URN'), ('DOI', 'DOI'), ('external', 'External')], max_length=16), blank=True, default=apps.core.models.data_catalog.default_allowed_pid_types, help_text='Persistent identifier types supported for datasets in catalog. External PIDs are not managed by Metax.', size=None),
        ),
        migrations.AddField(
            model_name='historicaldatacatalog',
            name='allowed_pid_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('URN', 'URN'), ('DOI', 'DOI'), ('external', 'External')], max_length=16), blank=True, default=apps.core.models.data_catalog.default_allowed_pid_types, help_text='Persistent identifier types supported for datasets in catalog. External PIDs are not managed by Metax.', size=None),
        ),
    ]
