# Generated by Django 4.2.16 on 2024-10-23 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_dataset_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preservation',
            name='state_modified',
            field=models.DateTimeField(blank=True, help_text='Last preservation state change', null=True),
        ),
        migrations.AddField(
            model_name='preservation',
            name='preservation_identifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='preservation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='legacy_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='legacy_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
