# Generated by Django 4.2.16 on 2024-12-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_preservation_state_modified_and_more'),
    ]

    operations = [
        # Convert Contract.id to CharField from UUIDField
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.CharField(editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='id',
            field=models.CharField(db_index=True, editable=False, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(
                check=models.Q(('id', ''), _negated=True),
                name='core_contract_require_nonempty_id'
            ),
        ),
        # Make Contract.contract_identifier nullable to make reverting
        # its deletion in a later migration easier
        migrations.AlterField(
            model_name='contract',
            name='contract_identifier',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='contract_identifier',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
