# Generated by Django 4.2.16 on 2024-12-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_replace_contract_id_values'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='core_contract_unique_contract_identifier',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_identifier',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='contract_identifier',
        ),
    ]
