# Generated by Django 4.2.16 on 2024-12-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_preservation_pas_package_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacatalog',
            name='rems_enabled',
            field=models.BooleanField(default=False, help_text='Is Resource entitlement management system enabled in catalog.'),
        ),
        migrations.AddField(
            model_name='historicaldatacatalog',
            name='rems_enabled',
            field=models.BooleanField(default=False, help_text='Is Resource entitlement management system enabled in catalog.'),
        ),
    ]
