# Generated by Django 4.2.16 on 2024-12-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_datacatalog_rems_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacatalog',
            old_name='harvested',
            new_name='is_external',
        ),
        migrations.RenameField(
            model_name='historicaldatacatalog',
            old_name='harvested',
            new_name='is_external',
        ),
    ]
