# Generated by Django 4.2.16 on 2024-12-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_harvested_datacatalog_is_external_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacatalog',
            name='rems_enabled',
            field=models.BooleanField(default=False, help_text='Is Resource Entitlement Management System enabled in catalog.'),
        ),
        migrations.AlterField(
            model_name='historicaldatacatalog',
            name='rems_enabled',
            field=models.BooleanField(default=False, help_text='Is Resource Entitlement Management System enabled in catalog.'),
        ),
    ]
