# Generated by Django 4.2.17 on 2025-02-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_accessrights_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrights',
            options={'get_latest_by': 'modified', 'ordering': ['created', 'id'], 'verbose_name_plural': 'Access rights'},
        ),
        migrations.AddField(
            model_name='datacatalog',
            name='allow_download',
            field=models.BooleanField(default=False, help_text='Allow downloading files of datasets in catalog.'),
        ),
        migrations.AddField(
            model_name='historicaldatacatalog',
            name='allow_download',
            field=models.BooleanField(default=False, help_text='Allow downloading files of datasets in catalog.'),
        ),
    ]
