# Generated by Django 4.2.17 on 2025-03-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_accessrights_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='V2SyncStatus',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('sync_started', models.DateTimeField(db_index=True, null=True)),
                ('sync_files_started', models.DateTimeField(null=True)),
                ('sync_stopped', models.DateTimeField(null=True)),
                ('action', models.TextField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('flush', 'Flush')], null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('dataset', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sync_status', to='core.dataset')),
            ],
            options={
                'verbose_name_plural': 'V2 sync statuses',
                'ordering': ['-sync_started'],
            },
        ),
    ]
