# Generated by Django 4.2.17 on 2025-03-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_v2syncstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSuccessfulV2Sync',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('record_modified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='v2syncstatus',
            name='action',
            field=models.TextField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('flush', 'Flush')], null=True),
        ),
    ]
