# Generated by Django 4.2.17 on 2025-03-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_lastsuccessfulv2sync_alter_v2syncstatus_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastsuccessfulv2sync',
            options={'ordering': ['-record_modified']},
        ),
    ]
