# Generated by Django 4.2.17 on 2025-03-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_lastsuccessfulv2sync_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preservation',
            name='state',
            field=models.IntegerField(default=-1, help_text='Record state in DPRES.'),
        ),
    ]
