# Generated by Django 4.2.17 on 2025-04-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_preservation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrights',
            name='rems_approval_type',
            field=models.TextField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], null=True),
        ),
        migrations.AddField(
            model_name='historicalaccessrights',
            name='rems_approval_type',
            field=models.TextField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], null=True),
        ),
    ]
