# Generated by Django 4.2.17 on 2025-04-23 10:22

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_dataset_rems_publish_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrights',
            name='data_access_application_instructions',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Instructions for applying for access to the data.', null=True),
        ),
        migrations.AddField(
            model_name='accessrights',
            name='data_access_reviewer_instructions',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Instructions for data access reviewers. Not shown to applicants.', null=True),
        ),
        migrations.AddField(
            model_name='accessrights',
            name='data_access_terms',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Terms a user needs to approve before getting access to the data.', null=True),
        ),
        migrations.AddField(
            model_name='historicalaccessrights',
            name='data_access_application_instructions',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Instructions for applying for access to the data.', null=True),
        ),
        migrations.AddField(
            model_name='historicalaccessrights',
            name='data_access_reviewer_instructions',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Instructions for data access reviewers. Not shown to applicants.', null=True),
        ),
        migrations.AddField(
            model_name='historicalaccessrights',
            name='data_access_terms',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Terms a user needs to approve before getting access to the data.', null=True),
        ),
    ]
