# Generated by Django 4.2.17 on 2025-05-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_accessrights_data_access_application_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataprovider',
            name='admin_organization',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
