# Generated by Django 4.2.17 on 2025-06-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_metadataprovider_admin_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrights',
            name='show_data_metadata',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccessrights',
            name='show_data_metadata',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
