# Generated by Django 4.2.17 on 2025-06-17 13:56

from django.db import migrations
from django.db.models import Q

def handle_IDA_data_metadata_visibility(apps, schema_editor):
    AccessRights=apps.get_model("core", "AccessRights")
    AccessRights.objects.filter(
        Q(dataset__data_catalog__storage_services__icontains="ida") | Q(dataset__data_catalog__storage_services__icontains="pas"),
        show_data_metadata__isnull=True
    ).update(show_data_metadata=True)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_accessrights_show_data_metadata_and_more'),
    ]

    operations = [
        migrations.RunPython(handle_IDA_data_metadata_visibility, migrations.RunPython.noop)
    ]
