# Generated by Django 4.2.17 on 2025-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20250617_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrights',
            name='show_data_metadata',
            field=models.BooleanField(blank=True, default=None, help_text='IDA-catalog only. Show/hide data metadata (file- and folder names, and other metadata, but not file amounts and sizes).', null=True),
        ),
        migrations.AlterField(
            model_name='historicalaccessrights',
            name='show_data_metadata',
            field=models.BooleanField(blank=True, default=None, help_text='IDA-catalog only. Show/hide data metadata (file- and folder names, and other metadata, but not file amounts and sizes).', null=True),
        ),
    ]
