# Generated by Django 4.2.17 on 2025-07-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_accessrights_show_data_metadata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrights',
            old_name='show_data_metadata',
            new_name='show_file_metadata',
        ),
        migrations.RenameField(
            model_name='historicalaccessrights',
            old_name='show_data_metadata',
            new_name='show_file_metadata',
        )
    ]
