# Generated by Django 5.2.7 on 2025-10-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_dataset_index_entry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetindexentry',
            options={'ordering': ['key', 'value', 'language']},
        ),
    ]
