# Generated by Django 4.2.24 on 2025-10-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_datasetindexentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='cached_total_files_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileset',
            name='cached_total_files_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileset',
            name='cached_totals_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
