# Generated by Django 4.2.24 on 2025-10-21 12:42

import apps.core.models.data_catalog
import django.contrib.postgres.fields
from django.db import migrations, models

def add_default_channel(apps, schema_editor):
    # Add "default" to catalogs that already have "etsin"
    model = apps.get_model("core", "DataCatalog")
    model.objects \
        .filter(publishing_channels__contains=["etsin"]) \
        .exclude(publishing_channels__contains=["default"]) \
        .update(publishing_channels=models.Func(
            models.Value('default'),
            models.F('publishing_channels'),
            function='array_prepend' # add to beginning of array
        ))



def remove_default_channel(apps, schema_editor):
    model = apps.get_model("core", "DataCatalog")
    model.objects \
        .filter(publishing_channels__contains=["default"]) \
        .update(publishing_channels=models.Func(
            models.F('publishing_channels'),
            models.Value('default'),
            function='array_remove' # remove all instances from array
        ))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_fileset_cached_total_files_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacatalog',
            name='publishing_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('etsin', 'etsin'), ('ttv', 'ttv'), ('default', 'default')], max_length=64), blank=True, default=apps.core.models.data_catalog.default_publishing_channels, help_text='Channels in which datasets in this catalog will be published.', size=None),
        ),
        migrations.AlterField(
            model_name='historicaldatacatalog',
            name='publishing_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('etsin', 'etsin'), ('ttv', 'ttv'), ('default', 'default')], max_length=64), blank=True, default=apps.core.models.data_catalog.default_publishing_channels, help_text='Channels in which datasets in this catalog will be published.', size=None),
        ),
        migrations.RunPython(add_default_channel, remove_default_channel)
    ]
