# Generated by Django 4.2.17 on 2025-10-14 06:12

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_alter_datacatalog_publishing_channels_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationStatistics",
            fields=[
                (
                    "id",
                    models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4),
                ),
                (
                    "organization",
                    models.CharField(max_length=200, unique=True, serialize=False),
                ),
                ("count_total", models.IntegerField(default=0)),
                ("count_ida", models.IntegerField(default=0)),
                ("count_pas", models.IntegerField(default=0)),
                ("count_att", models.IntegerField(default=0)),
                ("count_other", models.IntegerField(default=0)),
                ("byte_size_total", models.BigIntegerField(default=0)),
                ("byte_size_ida", models.BigIntegerField(default=0)),
                ("byte_size_pas", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectStatistics",
            fields=[
                (
                    "id",
                    models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4),
                ),
                (
                    "project_identifier",
                    models.CharField(max_length=200, unique=True, serialize=False),
                ),
                ("ida_count", models.IntegerField()),
                ("ida_byte_size", models.BigIntegerField()),
                ("ida_published_datasets", ArrayField(models.TextField(), default=list)),
                ("pas_count", models.IntegerField(default=0)),
                ("pas_byte_size", models.BigIntegerField(default=0)),
                ("pas_published_datasets", ArrayField(models.TextField(), default=list)),
            ],
        ),
    ]
