# Generated by Django 5.2.8 on 2025-11-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_organizationstatistics_projectstatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationstatistics',
            options={'ordering': ['organization']},
        ),
        migrations.AlterModelOptions(
            name='projectstatistics',
            options={'ordering': ['project_identifier']},
        ),
        migrations.AlterField(
            model_name='organizationstatistics',
            name='organization',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='projectstatistics',
            name='project_identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
