# Generated by Django 5.2.11 on 2026-03-13 14:09

import apps.refdata.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_geolocation'),
        ('refdata', '0005_sensitivityrationale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitivityRationale',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.refdata.models.ConceptProxyMixin, 'refdata.sensitivityrationale'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ContractSensitivityRationale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rationales', to='core.contract')),
                ('rationale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refdata.sensitivityrationale')),
            ],
        ),
    ]
