# Generated by Django 5.2.11 on 2026-03-26 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_dataset_organization_admin_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractsensitivityrationale',
            options={'ordering': ['-expiration_date']},
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DatasetSensitivityRationale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rationales', to='core.dataset')),
                ('rationale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensitivityrationale')),
            ],
            options={
                'ordering': ['-expiration_date'],
            },
        ),
    ]
