# Generated by Django 5.2.11 on 2026-04-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_contractsensitivityrationale_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsensitivityrationale',
            name='rationale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensitivityrationale'),
        ),
    ]
