# Generated by Django 5.2.13 on 2026-04-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_contractsensitivityrationale_rationale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacatalog',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='catalogs', to='core.language'),
        ),
    ]
