# Generated by Django 6.0.4 on 2026-05-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_datacatalog_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='geographic_type',
            field=models.IntegerField(choices=[(4, 'POINT'), (8, 'LINESTRING'), (12, 'POLYGON'), (16, 'MULTIPOINT'), (20, 'MULTILINESTRING'), (24, 'MULTIPOLYGON'), (28, 'GEOMETRYCOLLECTION')], default=0),
        ),
    ]
