# Generated by Django 6.0.4 on 2026-05-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_geolocation_geographic_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='geographic_type',
        ),
    ]
