# Generated by Django 6.0.4 on 2026-05-08 04:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_geolocation_geographic_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geolocation',
            old_name='geometry',
            new_name='geometry_2d',
        ),
        migrations.AddField(
            model_name='geolocation',
            name='geometry_3d',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, geography=True, null=True, srid=4326),
        ),
    ]
