# Generated by Django 6.0.4 on 2026-05-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_add_geometry_3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
