# Generated by Django 6.0.4 on 2026-05-26 07:24

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_geolocation_properties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteresource',
            name='byte_size',
            field=models.PositiveBigIntegerField(blank=True, help_text='File size in bytes.', null=True),
        ),
        migrations.CreateModel(
            name='DataService',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='example: {"fi":"otsikko","en":"title"}', null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_services', to='core.datacatalog')),
                ('system_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data service',
                'verbose_name_plural': 'data services',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='remoteresource',
            name='data_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dataservice'),
        ),
    ]
