# Generated by Django 3.2.21 on 2023-10-19 15:06

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    replaces = [('actors', '0001_initial'), ('actors', '0002_alter_actor_person'), ('actors', '0003_auto_20230807_1334'), ('actors', '0004_auto_20231019_1639'), ('actors', '0005_auto_20231019_1712')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refdata', '0002_auto_20221219_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=64, null=True)),
                ('in_scheme', models.URLField(max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('homepage', django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='example: {"title": {"en": "webpage"}, "identifier": "url"}', null=True)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='actors.organization')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_organizations', to='actors.organization')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors_actors', to=settings.AUTH_USER_MODEL)),
                ('person', models.CharField(max_length=512, null=True)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_reference_data'], name='actors_orga_is_refe_976e52_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['url'], name='actors_orga_url_2ac698_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('url', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='actors_organization_require_url'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='actors_organization_unique_organization_url'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('code', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='actors_organization_require_code'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('code',), name='actors_organization_unique_organization_code'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='actors_organization_require_reference_data_scheme'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='person',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=512)),
                ('email', models.EmailField(blank=True, max_length=512, null=True)),
                ('external_id', models.CharField(blank=True, help_text='External identifier for the actor, usually ORCID or similiar', max_length=512, null=True)),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actors_persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='actor',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_of_actor', to='actors.person'),
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_removed',
        ),
        migrations.AlterField(
            model_name='actor',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
