# Generated by Django 3.2.19 on 2023-05-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='person',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
