# Generated by Django 3.2.15 on 2022-10-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='actors_organization_require_url',
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('url', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='actors_organization_require_url'),
        ),
    ]
