# Generated by Django 3.2.22 on 2023-11-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20231026_1513'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organization',
            name='actors_organization_require_reference_data_scheme',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='external_id',
            new_name='external_identifier',
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='external_identifier',
            field=models.CharField(blank=True, help_text='External identifier for the organization.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_of_actors', to='actors.person'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='in_scheme',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme__isnull', False), models.Q(('in_scheme', ''), _negated=True)), ('is_reference_data', False), _connector='OR'), name='actors_organization_require_reference_data_scheme'),
        ),
    ]
