# Generated by Django 4.2.11 on 2024-03-25 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='homepage',
            field=models.OneToOneField(blank=True, help_text='example: {"title": {"en": "webpage"}, "url": "https://example.com"}', null=True, on_delete=django.db.models.deletion.SET_NULL, to='actors.homepage'),
        ),
    ]
