# Generated by Django 3.2.22 on 2024-02-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20231124_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'get_latest_by': 'modified', 'ordering': ['created', 'id']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'get_latest_by': 'modified', 'ordering': ['created', 'id']},
        ),
    ]
