# Generated by Django 4.2.17 on 2025-04-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rems', '0002_remslicense_custom_license_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='remsworkflow',
            name='metax_organization',
            field=models.CharField(blank=True, null=True),
        ),
    ]
