# Generated by Django 4.2.17 on 2025-05-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rems', '0003_remsworkflow_metax_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='remslicense',
            name='is_data_access_terms',
            field=models.BooleanField(default=False, help_text='True when license is generated from data_access_terms.'),
        ),
    ]
