CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 3600  # one year 31536000
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_SSL_REDIRECT = True
ENABLE_DEBUG_TOOLBAR = False
ENABLE_SILK_PROFILER = False

PID_MS_CLIENT_INSTANCE = "apps.core.services.pid_ms_client._PIDMSClient"

ALLOW_LOAD_TEST_DATA = False
ALLOW_LOAD_PAS_TEST_DATA = False
