# Generated by Django 4.2.11 on 2024-03-19 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('is_removed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('record_modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('storage_identifier', models.CharField(help_text='Identifier of file in external storage service', max_length=200, null=True)),
                ('filename', models.TextField()),
                ('directory_path', models.TextField(db_index=True)),
                ('size', models.BigIntegerField(default=0, help_text='File size in bytes.')),
                ('checksum', models.TextField(help_text="Checksum as a lowercase string in format 'algorithm:value'. Allowed algorithms: ['md5', 'sha256', 'sha512']")),
                ('frozen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('modified', models.DateTimeField()),
                ('removed', models.DateTimeField(blank=True, null=True)),
                ('is_pas_compatible', models.BooleanField(blank=True, default=None, null=True)),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['directory_path', 'filename'],
            },
        ),
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_service', models.CharField(choices=[('test', 'test'), ('ida', 'ida'), ('pas', 'pas'), ('legacy-test-storage-1', 'legacy-test-storage-1')], max_length=64)),
                ('csc_project', models.CharField(blank=True, max_length=200, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['created', 'id'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
