# Generated by Django 3.2.16 on 2023-02-08 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='system_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='system_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_filestorages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalfilestorage',
            name='system_creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storageproject',
            name='system_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_storageprojects', to=settings.AUTH_USER_MODEL),
        ),
    ]
