# Generated by Django 3.2.16 on 2023-02-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20230208_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='v2_identifier',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
