# Generated by Django 4.2.11 on 2024-05-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name=',files_file_unique_file_path',
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='files_file_unique_identifier',
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('removed__isnull', True)), fields=('filename', 'directory_path', 'storage'), name='files_file_unique_file_path'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('removed__isnull', True), ('storage_identifier__isnull', False)), fields=('storage_identifier', 'storage'), name='files_file_unique_identifier'),
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_removed',
        ),
    ]
