# Generated by Django 3.2.16 on 2023-02-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_v2_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_deleted',
            new_name='date_deleted',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_frozen',
            new_name='date_frozen',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_uploaded',
            new_name='date_uploaded',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='pas_compatible',
            new_name='is_pas_compatible',
        ),
    ]
