# Generated by Django 4.2.11 on 2024-05-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
