# Generated by Django 3.2.16 on 2023-02-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20230210_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='is_pas_compatible',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
