# Generated by Django 3.2.16 on 2023-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_file_is_pas_compatible'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('file_name', 'directory_path', 'storage_project'), name='files_file_unique_file_path_id'),
        ),
    ]
