# Generated by Django 4.2.11 on 2024-09-04 09:51

import apps.refdata.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0005_file_legacy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFormatVersion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(apps.refdata.models.ConceptProxyMixin, 'refdata.fileformatversion'),
        ),
        migrations.AddField(
            model_name='file',
            name='characteristics_extension',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FileCharacteristics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encoding', models.CharField(blank=True, choices=[('UTF-8', 'UTF-8'), ('UTF-16', 'UTF-16'), ('UTF-32', 'UTF-32'), ('ISO-8859-15', 'ISO-8859-15')], max_length=64, null=True)),
                ('csv_has_header', models.BooleanField(blank=True, null=True)),
                ('csv_quoting_char', models.CharField(blank=True, max_length=8, null=True)),
                ('csv_delimiter', models.CharField(blank=True, choices=[('\t', 'Tab'), (' ', 'Space'), (';', 'Semicolon'), (',', 'Comma'), (':', 'Colon'), ('.', 'Period'), ('|', 'Pipe')], max_length=8, null=True)),
                ('csv_record_separator', models.CharField(blank=True, choices=[('LF', 'LF'), ('CR', 'CR'), ('CRLF', 'CRLF')], max_length=8, null=True)),
                ('file_format_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_characteristics', to='files.fileformatversion')),
                ('system_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='file',
            name='characteristics',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file', to='files.filecharacteristics'),
        ),
    ]
