# Generated by Django 4.2.16 on 2024-11-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_fileformatversion_file_characteristics_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_legacy_syncable',
            field=models.BooleanField(default=True),
        ),
    ]
