# Generated by Django 3.2.18 on 2023-03-22 09:02

import apps.files.models.file_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20230310_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageproject',
            name='file_storage',
            field=models.CharField(max_length=64),
        ),
    ]
