# Generated by Django 4.2.16 on 2024-11-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_file_is_legacy_syncable'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pas_compatible_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_pas_compatible_file', to='files.file'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(check=models.Q(('pas_compatible_file', models.F('id')), _negated=True), name='files_file_no_self_pas_compatible_relation'),
        ),
    ]
