# Generated by Django 3.2.18 on 2023-03-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_storageproject_file_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfilestorage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfilestorage',
            name='system_creator',
        ),
        migrations.DeleteModel(
            name='FileStorage',
        ),
        migrations.DeleteModel(
            name='HistoricalFileStorage',
        ),
    ]
