# Generated by Django 4.2.16 on 2024-12-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_file_pas_compatible_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pas_process_running',
            field=models.BooleanField(default=False, help_text='Only PAS service is allowed to update files while PAS is processing them.'),
        ),
    ]
