# Generated by Django 3.2.18 on 2023-03-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20230322_1103'),
    ]

    operations = [
        migrations.RenameModel("StorageProject", "FileStorage")
    ]
