# Generated by Django 3.2.18 on 2023-04-17 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0009_auto_20230322_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicFileStorage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('files.filestorage',),
        ),
        migrations.CreateModel(
            name='ProjectFileStorage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('files.filestorage',),
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='files_file_unique_file_path_id',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='storage_project',
            new_name='file_storage',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='v2_identifier',
            new_name='file_storage_identifier',
        ),
        migrations.RenameField(
            model_name='filestorage',
            old_name='file_storage',
            new_name='storage_service',
        ),
        migrations.AddField(
            model_name='file',
            name='file_storage_pathname',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='project_identifier',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='system_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_filestorages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='filestorage',
            unique_together={('project_identifier', 'storage_service')},
        ),
        migrations.AlterIndexTogether(
            name='file',
            index_together={('directory_path', 'file_name'), ('directory_path', 'file_storage')},
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('file_name', 'directory_path', 'file_storage'), name='files_file_unique_file_path'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False), ('file_storage_identifier__isnull', False)), fields=('file_storage_identifier', 'file_storage'), name='files_file_unique_file_storage_identifier'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False), ('file_storage_pathname__isnull', False)), fields=('file_storage_pathname', 'file_storage'), name='files_file_unique_file_storage_pathname'),
        ),
        migrations.CreateModel(
            name='IDAFileStorage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('files.projectfilestorage',),
        ),
    ]
