# Generated by Django 5.2.7 on 2025-10-14 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_file_pas_process_running'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecharacteristics',
            options={'ordering': ['id'], 'verbose_name_plural': 'file characteristics'},
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='files_file_unique_file_path',
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='files_file_unique_identifier',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='files_file_directo_dfe580_idx',
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='files_file_directo_51da0a_idx',
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(condition=models.Q(('removed__isnull', True)), fields=['storage', 'directory_path'], name='files_file_storage_directory'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('removed__isnull', True)), fields=('storage', 'directory_path', 'filename'), name='files_file_unique_file_path'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('removed__isnull', True), ('storage_identifier__isnull', False)), fields=('storage', 'storage_identifier'), name='files_file_unique_identifier'),
        ),
    ]
