# Generated by Django 3.2.18 on 2023-04-21 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def assign_polymorphic_ctype(apps, schema_editor):
    file_storage_model = apps.get_model('files', "FileStorage")
    ContentType = apps.get_model('contenttypes', 'ContentType')
    for storage_service, model_name in settings.STORAGE_SERVICE_FILE_STORAGES.items():
        model = apps.get_model('files', model_name)
        new_ct = ContentType.objects.get_for_model(model, for_concrete_model=False)
        file_storage_model.objects.filter(storage_service=storage_service).update(polymorphic_ctype_id=new_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0010_auto_20230417_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_files.filestorage_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_storage_identifier',
            field=models.CharField(help_text='Identifier of file in external service', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_storage_pathname',
            field=models.CharField(help_text='Path of file in external service', max_length=4096, null=True),
        ),
        migrations.RunPython(assign_polymorphic_ctype, migrations.RunPython.noop),
    ]
