# Generated by Django 4.2.17 on 2025-10-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_update_file_constraints'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(condition=models.Q(('removed__isnull', True)), fields=['storage', 'directory_path'], include=('size', 'modified', 'published'), name='files_file_dir_aggregation', opclasses=['', 'text_pattern_ops']),
        ),
    ]
