# Generated by Django 3.2.19 on 2023-07-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_auto_20230421_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='project_identifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='storage_service',
            field=models.CharField(choices=[('test', 'test'), ('ida', 'ida'), ('pas', 'pas'), ('legacy-test-storage-1', 'legacy-test-storage-1')], max_length=64),
        ),
    ]
