# Generated by Django 4.2.24 on 2025-10-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_file_files_file_dir_aggregation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filestorage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='file',
            name='characteristics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file', to='files.filecharacteristics'),
        ),
        migrations.AddConstraint(
            model_name='filestorage',
            constraint=models.UniqueConstraint(fields=('storage_service', 'csc_project'), name='unique_storage_project'),
        ),
    ]
