# Generated by Django 3.2.19 on 2023-08-24 10:52

import django.core.validators
import django.utils.timezone
from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20230705_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='checksum',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='checksum_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='checksum_algorithm',
            field=models.CharField(default='', choices=[('SHA-256', 'SHA-256'), ('MD5', 'MD5'), ('SHA-512', 'SHA-512')], max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='checksum_value',
            field=models.TextField(default=''),
        ),
    ]
