# Generated by Django 4.2.24 on 2025-10-30 10:10

import apps.common.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_alter_filestorage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=apps.common.helpers.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
