# Generated by Django 5.2.8 on 2025-11-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecharacteristics',
            name='encoding',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
