# Generated by Django 3.2.19 on 2023-08-24 10:57

from django.db import migrations, models
from django.db.models.functions import Replace, Concat, Lower, Upper
from django.db.models import Value
from apps.files.functions import SplitPart

def checksum_obj_to_str(apps, schema_editor):
    """Convert checksum objects to strings.

    E.g. from {
      checksum_algorithm: 'SHA-256',
      checksum_value: 'X'
    } to {
      checksum: 'sha256:x'
    }
    """
    File = apps.get_model("files", "File")
    algo_fn = Replace(Lower('checksum_algorithm'), Value('-'), Value(''))
    File.objects.update(checksum=Concat(algo_fn, Value(':'), Lower('checksum_value')))


def checksum_str_to_obj(apps, schema_editor):
    """Reverse checksum conversion."""
    File = apps.get_model("files", "File")
    algo_fn = Upper(Replace(SplitPart(
        "checksum",
        Value(":"),
        1,
        output_field=models.CharField(),
    ), Value('sha'), Value('sha-')))
    value_fn = SplitPart(
        "checksum",
        Value(":"),
        2,
        output_field=models.CharField())
    File.objects.update(checksum_algorithm=algo_fn, checksum_value=value_fn)



class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_file_checksum'),
    ]

    operations = [
        migrations.RunPython(checksum_obj_to_str, checksum_str_to_obj),
        migrations.RemoveField(
            model_name='file',
            name='checksum_checked',
        ),
    ]
