# Generated by Django 3.2.19 on 2023-08-29 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0014_convert_checksum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['directory_path', 'filename']},
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='files_file_require_file_name',
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='files_file_unique_file_path',
        ),
        migrations.RemoveConstraint(
            model_name='file',
            name='files_file_unique_file_storage_identifier',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='date_frozen',
            new_name='frozen',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='created',
            new_name='record_created',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='modified',
            new_name='record_modified',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_storage',
            new_name='storage',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_storage_identifier',
            new_name='storage_identifier',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='byte_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_modified',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='filestorage',
            old_name='project_identifier',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='file',
            name='storage_identifier',
            field=models.CharField(help_text='Identifier of file in external storage service', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='checksum',
            field=models.TextField(help_text="Checksum as a lowercase string in format 'algorithm:value'. Allowed algorithms are: ['md5', 'sha256', 'sha512']"),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes.'),
        ),
        migrations.AlterUniqueTogether(
            name='filestorage',
            unique_together={('project', 'storage_service')},
        ),
        migrations.AlterIndexTogether(
            name='file',
            index_together={('directory_path', 'storage'), ('directory_path', 'filename')},
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.CheckConstraint(check=models.Q(('filename', ''), _negated=True), name='files_file_require_filename'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False)), fields=('filename', 'directory_path', 'storage'), name=',files_file_unique_file_path'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('is_removed', False), ('storage_identifier__isnull', False)), fields=('storage_identifier', 'storage'), name='files_file_unique_identifier'),
        ),
        migrations.RemoveField(
            model_name='file',
            name='checksum_algorithm',
        ),
        migrations.RemoveField(
            model_name='file',
            name='checksum_value',
        ),
        migrations.RemoveField(
            model_name='file',
            name='date_deleted',
        ),
        migrations.RemoveField(
            model_name='file',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_storage_pathname',
        ),
    ]
