# Generated by Django 5.2.11 on 2026-02-16 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_alter_filecharacteristics_encoding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='files_file_dir_aggregation',
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(condition=models.Q(('removed__isnull', True)), fields=['storage', 'directory_path'], include=('size', 'modified', 'published', 'id'), name='files_file_dir_aggregation', opclasses=['', 'text_pattern_ops']),
        ),
    ]
