# Generated by Django 5.2.11 on 2026-03-03 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_remove_file_files_file_dir_aggregation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(condition=models.Q(('removed__isnull', True)), fields=['storage', 'record_created'], name='files_file_storage_rec_created'),
        ),
    ]
