# Generated by Django 3.2.20 on 2023-09-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_auto_20230829_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='checksum',
            field=models.TextField(help_text="Checksum as a lowercase string in format 'algorithm:value'. Allowed algorithms: ['md5', 'sha256', 'sha512']"),
        ),
    ]
