# Generated by Django 3.2.21 on 2023-10-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_alter_file_checksum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filestorage',
            old_name='removal_date',
            new_name='removed',
        ),
    ]
