# Generated by Django 5.2.11 on 2026-04-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_file_files_file_storage_rec_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
