# Generated by Django 3.2.21 on 2023-09-28 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0016_alter_file_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_filestorages', to=settings.AUTH_USER_MODEL),
        ),
    ]
