# Generated by Django 3.2.21 on 2023-10-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_rename_removal_date_filestorage_removed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorage',
            name='is_removed',
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
