# Generated by Django 3.2.22 on 2023-10-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_auto_20230928_1442'),
        ('files', '0018_auto_20231019_1712'),
    ]

    operations = [
    ]
