# Generated by Django 3.2.22 on 2023-11-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0020_alter_file_frozen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filestorage',
            old_name='project',
            new_name='csc_project',
        ),
        migrations.AlterUniqueTogether(
            name='filestorage',
            unique_together={('csc_project', 'storage_service')},
        ),
    ]
