# Generated by Django 3.2.22 on 2024-02-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0021_auto_20231121_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='is_pas_compatible',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
