# Generated by Django 3.2.22 on 2024-02-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0022_alter_file_is_pas_compatible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filestorage',
            options={'get_latest_by': 'modified', 'ordering': ['created', 'id']},
        ),
    ]
