# Generated by Django 4.2.11 on 2024-03-18 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0023_alter_filestorage_options'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='file',
            new_name='files_file_directo_dfe580_idx',
            old_fields=('directory_path', 'storage'),
        ),
        migrations.RenameIndex(
            model_name='file',
            new_name='files_file_directo_51da0a_idx',
            old_fields=('directory_path', 'filename'),
        ),
        migrations.AlterField(
            model_name='file',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
