# Generated by Django 3.2.21 on 2023-10-19 15:02

import apps.common.helpers
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    replaces = [('refdata', '0001_initial'), ('refdata', '0002_auto_20221219_0909'), ('refdata', '0003_auto_20230119_1253'), ('refdata', '0004_auto_20230208_0959'), ('refdata', '0005_language_essential_choice'), ('refdata', '0006_rename_essential_choice_language_is_essential_choice'), ('refdata', '0007_auto_20230328_1250'), ('refdata', '0005_auto_20230315_1529'), ('refdata', '0008_merge_0005_auto_20230315_1529_0007_auto_20230328_1250'), ('refdata', '0009_alter_location_as_wkt'), ('refdata', '0010_auto_20231019_1639'), ('refdata', '0011_auto_20231019_1712')]

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCategory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.UseCategory')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_usecategorys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestrictionGrounds',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.RestrictionGrounds')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_restrictiongroundss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'restriction grounds',
                'verbose_name_plural': 'restriction grounds',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.ResourceType')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_resourcetypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchInfra',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.ResearchInfra')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_researchinfras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.RelationType')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_relationtypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreservationEvent',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.PreservationEvent')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_preservationevents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('as_wkt', models.TextField(blank=True, default='')),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.Location')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.LifecycleEvent')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_lifecycleevents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('license', models.URLField(blank=True, default='', help_text='URL for user-readable license text.', max_length=255)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.License')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.Language')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.Keyword')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_keywords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.IdentifierType')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_identifiertypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FunderType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.FunderType')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_fundertypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.FileType')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_filetypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileFormatVersion',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('file_format', models.CharField(max_length=255)),
                ('format_version', models.CharField(blank=True, default='', max_length=255)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.FileFormatVersion')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_fileformatversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldOfScience',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.FieldOfScience')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_fieldofsciences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'field of science',
                'verbose_name_plural': 'fields of science',
            },
        ),
        migrations.CreateModel(
            name='EventOutcome',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.EventOutcome')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_eventoutcomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContributorType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.ContributorType')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_contributortypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContributorRole',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.ContributorRole')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_contributorroles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessType',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.AccessType')),
                ('system_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_accesstypes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='usecategory',
            index=models.Index(fields=['is_reference_data'], name='refdata_use_is_refe_258c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='usecategory',
            index=models.Index(fields=['url'], name='refdata_use_url_51546d_idx'),
        ),
        migrations.AddConstraint(
            model_name='usecategory',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_usecategory_require_url'),
        ),
        migrations.AddConstraint(
            model_name='usecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_usecategory_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='usecategory',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_usecategory_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='restrictiongrounds',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_restrictiongrounds_require_url'),
        ),
        migrations.AddConstraint(
            model_name='restrictiongrounds',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_restrictiongrounds_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='restrictiongrounds',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_restrictiongrounds_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='resourcetype',
            index=models.Index(fields=['is_reference_data'], name='refdata_res_is_refe_b13667_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcetype',
            index=models.Index(fields=['url'], name='refdata_res_url_3e28fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourcetype',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_resourcetype_require_url'),
        ),
        migrations.AddConstraint(
            model_name='resourcetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_resourcetype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='resourcetype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_resourcetype_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='researchinfra',
            index=models.Index(fields=['is_reference_data'], name='refdata_res_is_refe_220457_idx'),
        ),
        migrations.AddIndex(
            model_name='researchinfra',
            index=models.Index(fields=['url'], name='refdata_res_url_ed1f71_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchinfra',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_researchinfra_require_url'),
        ),
        migrations.AddConstraint(
            model_name='researchinfra',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_researchinfra_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='researchinfra',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_researchinfra_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='relationtype',
            index=models.Index(fields=['is_reference_data'], name='refdata_rel_is_refe_db9147_idx'),
        ),
        migrations.AddIndex(
            model_name='relationtype',
            index=models.Index(fields=['url'], name='refdata_rel_url_02ea69_idx'),
        ),
        migrations.AddConstraint(
            model_name='relationtype',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_relationtype_require_url'),
        ),
        migrations.AddConstraint(
            model_name='relationtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_relationtype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='relationtype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_relationtype_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='preservationevent',
            index=models.Index(fields=['is_reference_data'], name='refdata_pre_is_refe_b2967c_idx'),
        ),
        migrations.AddIndex(
            model_name='preservationevent',
            index=models.Index(fields=['url'], name='refdata_pre_url_4f46c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='preservationevent',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_preservationevent_require_url'),
        ),
        migrations.AddConstraint(
            model_name='preservationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_preservationevent_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='preservationevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_preservationevent_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_reference_data'], name='refdata_loc_is_refe_f1bb42_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['url'], name='refdata_loc_url_ca7c51_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_location_require_url'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_location_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_location_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='lifecycleevent',
            index=models.Index(fields=['is_reference_data'], name='refdata_lif_is_refe_43273d_idx'),
        ),
        migrations.AddIndex(
            model_name='lifecycleevent',
            index=models.Index(fields=['url'], name='refdata_lif_url_981fe3_idx'),
        ),
        migrations.AddConstraint(
            model_name='lifecycleevent',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_lifecycleevent_require_url'),
        ),
        migrations.AddConstraint(
            model_name='lifecycleevent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_lifecycleevent_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='lifecycleevent',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_lifecycleevent_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['is_reference_data'], name='refdata_lic_is_refe_3a418d_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['url'], name='refdata_lic_url_378f1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_license_require_url'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_license_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_license_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['is_reference_data'], name='refdata_lan_is_refe_cc2341_idx'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['url'], name='refdata_lan_url_8d6b40_idx'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_language_require_url'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_language_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_language_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['is_reference_data'], name='refdata_key_is_refe_cabe24_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['url'], name='refdata_key_url_ed89cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_keyword_require_url'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_keyword_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_keyword_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='identifiertype',
            index=models.Index(fields=['is_reference_data'], name='refdata_ide_is_refe_9811c0_idx'),
        ),
        migrations.AddIndex(
            model_name='identifiertype',
            index=models.Index(fields=['url'], name='refdata_ide_url_61520d_idx'),
        ),
        migrations.AddConstraint(
            model_name='identifiertype',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_identifiertype_require_url'),
        ),
        migrations.AddConstraint(
            model_name='identifiertype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_identifiertype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='identifiertype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_identifiertype_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='fundertype',
            index=models.Index(fields=['is_reference_data'], name='refdata_fun_is_refe_05b7ff_idx'),
        ),
        migrations.AddIndex(
            model_name='fundertype',
            index=models.Index(fields=['url'], name='refdata_fun_url_1d68d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundertype',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_fundertype_require_url'),
        ),
        migrations.AddConstraint(
            model_name='fundertype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_fundertype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='fundertype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_fundertype_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='filetype',
            index=models.Index(fields=['is_reference_data'], name='refdata_fil_is_refe_d9c48d_idx'),
        ),
        migrations.AddIndex(
            model_name='filetype',
            index=models.Index(fields=['url'], name='refdata_fil_url_a64f58_idx'),
        ),
        migrations.AddConstraint(
            model_name='filetype',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_filetype_require_url'),
        ),
        migrations.AddConstraint(
            model_name='filetype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_filetype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='filetype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_filetype_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='fileformatversion',
            index=models.Index(fields=['is_reference_data'], name='refdata_fil_is_refe_f619b5_idx'),
        ),
        migrations.AddIndex(
            model_name='fileformatversion',
            index=models.Index(fields=['url'], name='refdata_fil_url_2865b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileformatversion',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_fileformatversion_require_url'),
        ),
        migrations.AddConstraint(
            model_name='fileformatversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_fileformatversion_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='fileformatversion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_fileformatversion_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='fieldofscience',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_fieldofscience_require_url'),
        ),
        migrations.AddConstraint(
            model_name='fieldofscience',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_fieldofscience_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='fieldofscience',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_fieldofscience_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='eventoutcome',
            index=models.Index(fields=['is_reference_data'], name='refdata_eve_is_refe_7b8daf_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoutcome',
            index=models.Index(fields=['url'], name='refdata_eve_url_2394dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventoutcome',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_eventoutcome_require_url'),
        ),
        migrations.AddConstraint(
            model_name='eventoutcome',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_eventoutcome_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='eventoutcome',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_eventoutcome_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='contributortype',
            index=models.Index(fields=['is_reference_data'], name='refdata_con_is_refe_0ee707_idx'),
        ),
        migrations.AddIndex(
            model_name='contributortype',
            index=models.Index(fields=['url'], name='refdata_con_url_c3d422_idx'),
        ),
        migrations.AddConstraint(
            model_name='contributortype',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_contributortype_require_url'),
        ),
        migrations.AddConstraint(
            model_name='contributortype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_contributortype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='contributortype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_contributortype_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='contributorrole',
            index=models.Index(fields=['is_reference_data'], name='refdata_con_is_refe_122cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='contributorrole',
            index=models.Index(fields=['url'], name='refdata_con_url_bf3344_idx'),
        ),
        migrations.AddConstraint(
            model_name='contributorrole',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_contributorrole_require_url'),
        ),
        migrations.AddConstraint(
            model_name='contributorrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_contributorrole_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='contributorrole',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_contributorrole_require_reference_data_scheme'),
        ),
        migrations.AddIndex(
            model_name='accesstype',
            index=models.Index(fields=['is_reference_data'], name='refdata_acc_is_refe_315c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='accesstype',
            index=models.Index(fields=['url'], name='refdata_acc_url_a291d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='accesstype',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_accesstype_require_url'),
        ),
        migrations.AddConstraint(
            model_name='accesstype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_accesstype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='accesstype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_accesstype_require_reference_data_scheme'),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.Theme')),
                ('system_creator', models.ForeignKey(default=apps.common.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['is_reference_data'], name='refdata_the_is_refe_a40d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['url'], name='refdata_the_url_02fdee_idx'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_theme_require_url'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_theme_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_theme_require_reference_data_scheme'),
        ),
        migrations.AlterField(
            model_name='License',
            name='broader',
            field=models.ManyToManyField(blank=True, related_name='narrower', to='refdata.License'),
        ),
        migrations.RemoveField(
            model_name='license',
            name='license',
        ),
        migrations.AlterField(
            model_name='theme',
            name='system_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='fieldofscience',
            options={'get_latest_by': 'modified', 'ordering': ['created'], 'verbose_name': 'field of science', 'verbose_name_plural': 'fields of science'},
        ),
        migrations.AlterModelOptions(
            name='restrictiongrounds',
            options={'get_latest_by': 'modified', 'ordering': ['created'], 'verbose_name': 'restriction grounds', 'verbose_name_plural': 'restriction grounds'},
        ),
        migrations.AddIndex(
            model_name='fieldofscience',
            index=models.Index(fields=['is_reference_data'], name='refdata_fie_is_refe_efdd9f_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldofscience',
            index=models.Index(fields=['url'], name='refdata_fie_url_a5c66a_idx'),
        ),
        migrations.AddIndex(
            model_name='restrictiongrounds',
            index=models.Index(fields=['is_reference_data'], name='refdata_res_is_refe_35cdb5_idx'),
        ),
        migrations.AddIndex(
            model_name='restrictiongrounds',
            index=models.Index(fields=['url'], name='refdata_res_url_2b1384_idx'),
        ),
        migrations.AddField(
            model_name='language',
            name='is_essential_choice',
            field=models.BooleanField(default=False, help_text='If the language should be selectable in model forms'),
        ),
        migrations.AddField(
            model_name='fieldofscience',
            name='is_essential_choice',
            field=models.BooleanField(default=False, help_text='If the field of science should be selectable in model forms'),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_essential_choice',
            field=models.BooleanField(default=False, help_text='If the theme should be selectable in model forms'),
        ),
        migrations.RemoveConstraint(
            model_name='accesstype',
            name='refdata_accesstype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='accesstype',
            name='refdata_accesstype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='contributorrole',
            name='refdata_contributorrole_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='contributorrole',
            name='refdata_contributorrole_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='contributortype',
            name='refdata_contributortype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='contributortype',
            name='refdata_contributortype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='eventoutcome',
            name='refdata_eventoutcome_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='eventoutcome',
            name='refdata_eventoutcome_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='fieldofscience',
            name='refdata_fieldofscience_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='fieldofscience',
            name='refdata_fieldofscience_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='fileformatversion',
            name='refdata_fileformatversion_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='fileformatversion',
            name='refdata_fileformatversion_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='filetype',
            name='refdata_filetype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='filetype',
            name='refdata_filetype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='fundertype',
            name='refdata_fundertype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='fundertype',
            name='refdata_fundertype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='identifiertype',
            name='refdata_identifiertype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='identifiertype',
            name='refdata_identifiertype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='language',
            name='refdata_language_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='language',
            name='refdata_language_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='license',
            name='refdata_license_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='license',
            name='refdata_license_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='lifecycleevent',
            name='refdata_lifecycleevent_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='lifecycleevent',
            name='refdata_lifecycleevent_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='refdata_location_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='refdata_location_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='preservationevent',
            name='refdata_preservationevent_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='preservationevent',
            name='refdata_preservationevent_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='relationtype',
            name='refdata_relationtype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='relationtype',
            name='refdata_relationtype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='researchinfra',
            name='refdata_researchinfra_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='researchinfra',
            name='refdata_researchinfra_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='resourcetype',
            name='refdata_resourcetype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='resourcetype',
            name='refdata_resourcetype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='restrictiongrounds',
            name='refdata_restrictiongrounds_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='restrictiongrounds',
            name='refdata_restrictiongrounds_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='theme',
            name='refdata_theme_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='theme',
            name='refdata_theme_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='usecategory',
            name='refdata_usecategory_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='usecategory',
            name='refdata_usecategory_require_reference_data_scheme',
        ),
        migrations.RemoveIndex(
            model_name='accesstype',
            name='refdata_acc_is_refe_315c3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='contributorrole',
            name='refdata_con_is_refe_122cb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='contributortype',
            name='refdata_con_is_refe_0ee707_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventoutcome',
            name='refdata_eve_is_refe_7b8daf_idx',
        ),
        migrations.RemoveIndex(
            model_name='fieldofscience',
            name='refdata_fie_is_refe_efdd9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileformatversion',
            name='refdata_fil_is_refe_f619b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='filetype',
            name='refdata_fil_is_refe_d9c48d_idx',
        ),
        migrations.RemoveIndex(
            model_name='fundertype',
            name='refdata_fun_is_refe_05b7ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='identifiertype',
            name='refdata_ide_is_refe_9811c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='language',
            name='refdata_lan_is_refe_cc2341_idx',
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='refdata_lic_is_refe_3a418d_idx',
        ),
        migrations.RemoveIndex(
            model_name='lifecycleevent',
            name='refdata_lif_is_refe_43273d_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='refdata_loc_is_refe_f1bb42_idx',
        ),
        migrations.RemoveIndex(
            model_name='preservationevent',
            name='refdata_pre_is_refe_b2967c_idx',
        ),
        migrations.RemoveIndex(
            model_name='relationtype',
            name='refdata_rel_is_refe_db9147_idx',
        ),
        migrations.RemoveIndex(
            model_name='researchinfra',
            name='refdata_res_is_refe_220457_idx',
        ),
        migrations.RemoveIndex(
            model_name='resourcetype',
            name='refdata_res_is_refe_b13667_idx',
        ),
        migrations.RemoveIndex(
            model_name='restrictiongrounds',
            name='refdata_res_is_refe_35cdb5_idx',
        ),
        migrations.RemoveIndex(
            model_name='theme',
            name='refdata_the_is_refe_a40d9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='usecategory',
            name='refdata_use_is_refe_258c7e_idx',
        ),
        migrations.RemoveField(
            model_name='accesstype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='contributorrole',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='contributortype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='eventoutcome',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='fieldofscience',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='fileformatversion',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='filetype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='fundertype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='identifiertype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='language',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='license',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='lifecycleevent',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='preservationevent',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='relationtype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='researchinfra',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='resourcetype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='restrictiongrounds',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='usecategory',
            name='is_reference_data',
        ),
        migrations.AddConstraint(
            model_name='accesstype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_accesstype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='accesstype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_accesstype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='contributorrole',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_contributorrole_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='contributorrole',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_contributorrole_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='contributortype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_contributortype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='contributortype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_contributortype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='eventoutcome',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_eventoutcome_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='eventoutcome',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_eventoutcome_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='fieldofscience',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_fieldofscience_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='fieldofscience',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_fieldofscience_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='fileformatversion',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_fileformatversion_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='fileformatversion',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_fileformatversion_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='filetype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_filetype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='filetype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_filetype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='fundertype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_fundertype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='fundertype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_fundertype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='identifiertype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_identifiertype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='identifiertype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_identifiertype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_language_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_language_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_license_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_license_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='lifecycleevent',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_lifecycleevent_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='lifecycleevent',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_lifecycleevent_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_location_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_location_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='preservationevent',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_preservationevent_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='preservationevent',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_preservationevent_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='relationtype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_relationtype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='relationtype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_relationtype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='researchinfra',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_researchinfra_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='researchinfra',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_researchinfra_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='resourcetype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_resourcetype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='resourcetype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_resourcetype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='restrictiongrounds',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_restrictiongrounds_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='restrictiongrounds',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_restrictiongrounds_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_theme_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_theme_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='usecategory',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_usecategory_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='usecategory',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_usecategory_require_reference_data_scheme'),
        ),
        migrations.AlterField(
            model_name='location',
            name='as_wkt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='accesstype',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='contributorrole',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='contributortype',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='eventoutcome',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='fieldofscience',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='fileformatversion',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='filetype',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='fundertype',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='identifiertype',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='lifecycleevent',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='preservationevent',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='relationtype',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='researchinfra',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='resourcetype',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='restrictiongrounds',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RenameField(
            model_name='usecategory',
            old_name='removal_date',
            new_name='removed',
        ),
        migrations.RemoveField(
            model_name='accesstype',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='contributorrole',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='contributortype',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='eventoutcome',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='fieldofscience',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='fileformatversion',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='filetype',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='fundertype',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='identifiertype',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='language',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='license',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='lifecycleevent',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='preservationevent',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='relationtype',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='researchinfra',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='resourcetype',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='restrictiongrounds',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='usecategory',
            name='is_removed',
        ),
        migrations.AlterField(
            model_name='accesstype',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contributorrole',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contributortype',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='eventoutcome',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='fieldofscience',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='fileformatversion',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='fundertype',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='identifiertype',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='lifecycleevent',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='preservationevent',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='researchinfra',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='restrictiongrounds',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='usecategory',
            name='removed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
