# Generated by Django 3.2.12 on 2022-06-07 10:01

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfScience',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.FieldOfScience')),
            ],
            options={
                'verbose_name': 'field of science',
                'verbose_name_plural': 'fields of science',
            },
        ),
        migrations.AddConstraint(
            model_name='fieldofscience',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_fieldofscience_require_url'),
        ),
        migrations.AddConstraint(
            model_name='fieldofscience',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_fieldofscience_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='fieldofscience',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_fieldofscience_require_reference_data_scheme'),
        ),
    ]
