# Generated by Django 3.2.16 on 2022-12-19 07:09

import apps.core.helpers
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_reference_data', models.BooleanField(default=False)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.Theme')),
                ('system_creator', models.ForeignKey(default=apps.core.helpers.get_technical_metax_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['is_reference_data'], name='refdata_the_is_refe_a40d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='theme',
            index=models.Index(fields=['url'], name='refdata_the_url_02fdee_idx'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(check=models.Q(('url', ''), _negated=True), name='refdata_theme_require_url'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference_data', True)), fields=('url',), name='refdata_theme_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('in_scheme', ''), _negated=True), ('is_reference_data', False), _connector='OR'), name='refdata_theme_require_reference_data_scheme'),
        ),
    ]
