# Generated by Django 3.2.22 on 2023-10-26 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refdata', '0001_squashed_0011_auto_20231019_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstype',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_accesstypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributorrole',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_contributorroles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributortype',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_contributortypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventoutcome',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_eventoutcomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldofscience',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_fieldofsciences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileformatversion',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_fileformatversions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_filetypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundertype',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_fundertypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identifiertype',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_identifiertypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='language',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_languages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='license',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_licenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lifecycleevent',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_lifecycleevents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preservationevent',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_preservationevents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_relationtypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researchinfra',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_researchinfras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_resourcetypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restrictiongrounds',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_restrictiongroundss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theme',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usecategory',
            name='system_creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_usecategorys', to=settings.AUTH_USER_MODEL),
        ),
    ]
