# Generated by Django 3.2.16 on 2023-01-19 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230119_1253'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('refdata', '0002_auto_20221219_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='License',
            name='broader',
            field=models.ManyToManyField(blank=True, related_name='narrower', to='refdata.License'),
        ),
        migrations.RemoveField(
            model_name='license',
            name='license',
        ),
        migrations.AlterField(
            model_name='theme',
            name='system_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refdata_themes', to=settings.AUTH_USER_MODEL),
        ),
    ]
