# Generated by Django 3.2.22 on 2024-03-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0002_auto_20231026_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstype',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='contributorrole',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='contributortype',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='eventoutcome',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='fieldofscience',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='fileformatversion',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='filetype',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='fundertype',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='identifiertype',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='lifecycleevent',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='preservationevent',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='researchinfra',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='restrictiongrounds',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
        migrations.AddField(
            model_name='usecategory',
            name='deprecated',
            field=models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True),
        ),
    ]
