# Generated by Django 5.2.8 on 2025-11-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0003_remove_fieldofscience_is_essential_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileformatversion',
            name='allowed_encodings',
            field=models.JSONField(default=list),
        ),
    ]
