# Generated by Django 3.2.16 on 2023-03-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0004_auto_20230208_0959'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accesstype',
            name='refdata_accesstype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='accesstype',
            name='refdata_accesstype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='contributorrole',
            name='refdata_contributorrole_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='contributorrole',
            name='refdata_contributorrole_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='contributortype',
            name='refdata_contributortype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='contributortype',
            name='refdata_contributortype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='eventoutcome',
            name='refdata_eventoutcome_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='eventoutcome',
            name='refdata_eventoutcome_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='fieldofscience',
            name='refdata_fieldofscience_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='fieldofscience',
            name='refdata_fieldofscience_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='fileformatversion',
            name='refdata_fileformatversion_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='fileformatversion',
            name='refdata_fileformatversion_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='filetype',
            name='refdata_filetype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='filetype',
            name='refdata_filetype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='fundertype',
            name='refdata_fundertype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='fundertype',
            name='refdata_fundertype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='identifiertype',
            name='refdata_identifiertype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='identifiertype',
            name='refdata_identifiertype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='language',
            name='refdata_language_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='language',
            name='refdata_language_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='license',
            name='refdata_license_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='license',
            name='refdata_license_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='lifecycleevent',
            name='refdata_lifecycleevent_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='lifecycleevent',
            name='refdata_lifecycleevent_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='refdata_location_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='refdata_location_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='preservationevent',
            name='refdata_preservationevent_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='preservationevent',
            name='refdata_preservationevent_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='relationtype',
            name='refdata_relationtype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='relationtype',
            name='refdata_relationtype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='researchinfra',
            name='refdata_researchinfra_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='researchinfra',
            name='refdata_researchinfra_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='resourcetype',
            name='refdata_resourcetype_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='resourcetype',
            name='refdata_resourcetype_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='restrictiongrounds',
            name='refdata_restrictiongrounds_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='restrictiongrounds',
            name='refdata_restrictiongrounds_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='theme',
            name='refdata_theme_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='theme',
            name='refdata_theme_require_reference_data_scheme',
        ),
        migrations.RemoveConstraint(
            model_name='usecategory',
            name='refdata_usecategory_unique_reference_data_url',
        ),
        migrations.RemoveConstraint(
            model_name='usecategory',
            name='refdata_usecategory_require_reference_data_scheme',
        ),
        migrations.RemoveIndex(
            model_name='accesstype',
            name='refdata_acc_is_refe_315c3a_idx',
        ),
        migrations.RemoveIndex(
            model_name='contributorrole',
            name='refdata_con_is_refe_122cb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='contributortype',
            name='refdata_con_is_refe_0ee707_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventoutcome',
            name='refdata_eve_is_refe_7b8daf_idx',
        ),
        migrations.RemoveIndex(
            model_name='fieldofscience',
            name='refdata_fie_is_refe_efdd9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='fileformatversion',
            name='refdata_fil_is_refe_f619b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='filetype',
            name='refdata_fil_is_refe_d9c48d_idx',
        ),
        migrations.RemoveIndex(
            model_name='fundertype',
            name='refdata_fun_is_refe_05b7ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='identifiertype',
            name='refdata_ide_is_refe_9811c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='language',
            name='refdata_lan_is_refe_cc2341_idx',
        ),
        migrations.RemoveIndex(
            model_name='license',
            name='refdata_lic_is_refe_3a418d_idx',
        ),
        migrations.RemoveIndex(
            model_name='lifecycleevent',
            name='refdata_lif_is_refe_43273d_idx',
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='refdata_loc_is_refe_f1bb42_idx',
        ),
        migrations.RemoveIndex(
            model_name='preservationevent',
            name='refdata_pre_is_refe_b2967c_idx',
        ),
        migrations.RemoveIndex(
            model_name='relationtype',
            name='refdata_rel_is_refe_db9147_idx',
        ),
        migrations.RemoveIndex(
            model_name='researchinfra',
            name='refdata_res_is_refe_220457_idx',
        ),
        migrations.RemoveIndex(
            model_name='resourcetype',
            name='refdata_res_is_refe_b13667_idx',
        ),
        migrations.RemoveIndex(
            model_name='restrictiongrounds',
            name='refdata_res_is_refe_35cdb5_idx',
        ),
        migrations.RemoveIndex(
            model_name='theme',
            name='refdata_the_is_refe_a40d9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='usecategory',
            name='refdata_use_is_refe_258c7e_idx',
        ),
        migrations.RemoveField(
            model_name='accesstype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='contributorrole',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='contributortype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='eventoutcome',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='fieldofscience',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='fileformatversion',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='filetype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='fundertype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='identifiertype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='language',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='license',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='lifecycleevent',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='preservationevent',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='relationtype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='researchinfra',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='resourcetype',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='restrictiongrounds',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='is_reference_data',
        ),
        migrations.RemoveField(
            model_name='usecategory',
            name='is_reference_data',
        ),
        migrations.AddConstraint(
            model_name='accesstype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_accesstype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='accesstype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_accesstype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='contributorrole',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_contributorrole_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='contributorrole',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_contributorrole_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='contributortype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_contributortype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='contributortype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_contributortype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='eventoutcome',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_eventoutcome_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='eventoutcome',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_eventoutcome_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='fieldofscience',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_fieldofscience_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='fieldofscience',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_fieldofscience_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='fileformatversion',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_fileformatversion_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='fileformatversion',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_fileformatversion_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='filetype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_filetype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='filetype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_filetype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='fundertype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_fundertype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='fundertype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_fundertype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='identifiertype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_identifiertype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='identifiertype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_identifiertype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_language_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_language_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_license_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_license_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='lifecycleevent',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_lifecycleevent_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='lifecycleevent',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_lifecycleevent_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_location_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_location_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='preservationevent',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_preservationevent_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='preservationevent',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_preservationevent_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='relationtype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_relationtype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='relationtype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_relationtype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='researchinfra',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_researchinfra_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='researchinfra',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_researchinfra_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='resourcetype',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_resourcetype_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='resourcetype',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_resourcetype_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='restrictiongrounds',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_restrictiongrounds_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='restrictiongrounds',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_restrictiongrounds_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_theme_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='theme',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_theme_require_reference_data_scheme'),
        ),
        migrations.AddConstraint(
            model_name='usecategory',
            constraint=models.UniqueConstraint(fields=('url',), name='refdata_usecategory_unique_reference_data_url'),
        ),
        migrations.AddConstraint(
            model_name='usecategory',
            constraint=models.CheckConstraint(check=models.Q(('in_scheme', ''), _negated=True), name='refdata_usecategory_require_reference_data_scheme'),
        ),
    ]
