# Generated by Django 3.2.18 on 2023-03-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0004_auto_20230208_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='essential_choice',
            field=models.BooleanField(default=False, help_text='If the language should be selectable in model forms'),
        ),
    ]
