# Generated by Django 5.2.11 on 2026-03-10 10:44

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0004_fileformatversion_allowed_encodings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitivityRationale',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('removed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=255)),
                ('in_scheme', models.URLField(blank=True, default='', max_length=255)),
                ('pref_label', django.contrib.postgres.fields.hstore.HStoreField(help_text='example: {"en":"title", "fi":"otsikko"}')),
                ('same_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('deprecated', models.DateTimeField(blank=True, help_text='If set, entry is not shown in reference data list by default.', null=True)),
                ('broader', models.ManyToManyField(blank=True, related_name='narrower', to='refdata.sensitivityrationale')),
                ('system_creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'get_latest_by': 'modified',
                'abstract': False,
                'indexes': [models.Index(fields=['url'], name='refdata_sen_url_bf17f3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('url', ''), _negated=True), name='refdata_sensitivityrationale_require_url'), models.UniqueConstraint(fields=('url',), name='refdata_sensitivityrationale_unique_reference_data_url'), models.CheckConstraint(condition=models.Q(('in_scheme', ''), _negated=True), name='refdata_sensitivityrationale_require_reference_data_scheme')],
            },
        ),
    ]
