# Generated by Django 3.2.18 on 2023-03-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0005_language_essential_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='essential_choice',
            new_name='is_essential_choice',
        ),
    ]
