# Generated by Django 3.2.18 on 2023-03-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0006_rename_essential_choice_language_is_essential_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldofscience',
            name='is_essential_choice',
            field=models.BooleanField(default=False, help_text='If the field of science should be selectable in model forms'),
        ),
        migrations.AddField(
            model_name='theme',
            name='is_essential_choice',
            field=models.BooleanField(default=False, help_text='If the theme should be selectable in model forms'),
        ),
    ]
