# Generated by Django 3.2.18 on 2023-04-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0005_auto_20230315_1529'),
        ('refdata', '0007_auto_20230328_1250'),
    ]

    operations = [
    ]
